# 0. Setup

In [ ]:
import os

os.environ["HF_TOKEN"] = "SECRET_KEY"

# 1. Retrieving

In [2]:
from src.preprocess_parquet import load
import pandas as pd


df = load('data/processed/phapdien_processed.parquet')
# df = df.drop(columns=['docs_vbpl_id', 'docs_title', 'status', 'agency_name', 'topic_title', 'source_links'])
df

,legal_type,docs_code,docs_title,article_index,article_title,source_note_text,source_links,topic_title,subject_title,content_text,content_word_count,content_clause_count
40313,Thông tư,18/2023/TT-BTC,Thông tư số 18/2023/TT-BTC,Điều 6,Điều 39.13.TT.70.6. Cách tính và thực hiện bù ...,"(Điều 6 Thông tư số 18/2023/TT-BTC, có hiệu lự...","[{'text': '(Điều 6 Thông tư số 18/2023/TT-BTC,...","Trật tự, an toàn xã hội",Xử lý vi phạm hành chính,"{'title': '', 'content': [{'text': '1. Cách tí...",1735769,63
27764,Nghị định,38/2016/NĐ-CP,Nghị định số 38/2016/NĐ-CP,Điều 8,Điều 27.2.NĐ.1.8. Bảo vệ hành lang kỹ thuật cô...,"(Điều 8 Nghị định số 38/2016/NĐ-CP, có hiệu lự...","[{'text': '(Điều 8 Nghị định số 38/2016/NĐ-CP,...",Tài nguyên,Khí tượng thủy văn,"{'title': '', 'content': [{'title': '1. Bảo vệ...",116725,22
22725,Thông tư,36/2014/TT-BNNPTNT,Thông tư số 36/2014/TT-BNNPTNT,Điều 2,Điều 24.1.TT.12.2. Giải thích từ ngữ,"(Điều 2 Thông tư số 36/2014/TT-BNNPTNT, có hiệ...",[{'text': '(Điều 2 Thông tư số 36/2014/TT-BNNP...,"Nông nghiệp, nông thôn",Bảo vệ và kiểm dịch thực vật,"{'title': 'Trong Thông tư này, các từ ngữ dưới...",95736,30
18195,Nghị định,145/2020/NĐ-CP,Nghị định số 145/2020/NĐ-CP,Điều 57,Điều 20.2.NĐ.3.57. Tiền lương làm thêm giờ vào...,"(Điều 57 Nghị định số 145/2020/NĐ-CP, có hiệu ...",[{'text': '(Điều 57 Nghị định số 145/2020/NĐ-C...,Lao động,Lao động,{'title': 'Người lao động làm thêm giờ vào ban...,89094,14
2096,Thông tư,20/2017/TT-BTTTT,Thông tư số 20/2017/TT-BTTTT,Điều 3,Điều 3.1.TT.3.3. Phân cấp tổ chức thực hiện ứn...,"(Điều 3 Thông tư số 20/2017/TT-BTTTT, có hiệu ...",[{'text': '(Điều 3 Thông tư số 20/2017/TT-BTTT...,"Bưu chính, viễn thông",An toàn thông tin mạng,{'title': 'Phân cấp tổ chức thực hiện ứng cứu ...,64554,14
...,...,...,...,...,...,...,...,...,...,...,...,...
27708,Thông tư,21/2016/TT-BTNMT,Thông tư số 21/2016/TT-BTNMT,Điều 1,Điều 27.1.TT.53.1. Ban hành kèm theo Thông tư ...,(Điều 1 Thông tư số 21/2016/TT-BTNMT Ban hành ...,[{'text': '(Điều 1 Thông tư số 21/2016/TT-BTNM...,Tài nguyên,Đo đạc và bản đồ,{'text': 'Danh muc_21_2016_TT-BTNMT.doc'},2,0
27716,Thông tư,19/2017/TT-BTNMT,Thông tư số 19/2017/TT-BTNMT,Điều 1,Điều 27.1.TT.62.1. Ban hành kèm theo Thông tư ...,(Điều 1 Thông tư số 19/2017/TT-BTNMT Ban hành ...,[{'text': '(Điều 1 Thông tư số 19/2017/TT-BTNM...,Tài nguyên,Đo đạc và bản đồ,{'text': 'Danh muc_19_2017_TT-BTNMT.doc'},2,0
27718,Thông tư,48/2013/TT-BTNMT,Thông tư số 48/2013/TT-BTNMT,Điều 1,Điều 27.1.TT.26.1. Ban hành kèm theo Thông tư ...,(Điều 1 Thông tư số 48/2013/TT-BTNMT Ban hành ...,[{'text': '(Điều 1 Thông tư số 48/2013/TT-BTNM...,Tài nguyên,Đo đạc và bản đồ,{'text': 'Danh muc_48_2013_TT-BTNMT.doc'},2,0
27691,Thông tư,38/2013/TT-BTNMT,Thông tư số 38/2013/TT-BTNMT,Điều 1,Điều 27.1.TT.21.1. Ban hành kèm theo Thông tư ...,(Điều 1 Thông tư số 38/2013/TT-BTNMT Ban hành ...,[{'text': '(Điều 1 Thông tư số 38/2013/TT-BTNM...,Tài nguyên,Đo đạc và bản đồ,{'text': 'Danh muc_38_2013_TT-BTNMT.doc'},2,0
44248,Thông tư,04/2018/TT-BXD,Thông tư số 04/2018/TT-BXD,Điều 1,Điều 41.9.TT.4.1. Ban hành kèm theo Thông tư n...,(Điều 1 Thông tư số 04/2018/TT-BXD Ban hành Qu...,[{'text': '(Điều 1 Thông tư số 04/2018/TT-BXD ...,"Văn hóa, thể thao, du lịch",Quảng cáo,{'text': 'QuychuankemThongtu04-2018-BXD.doc'},1,0

In [3]:
from src.recall_retriever import BM25
from src.data_presentation import Corpus, HierarchicalCorpus

corpus_simple = Corpus()
corpus_hier = HierarchicalCorpus(
    alpha = 0.5,
    title_blending = True
)

bm25_raw = BM25(
    name="BM25_ra",
    corpus= corpus_simple,
    top_k=100,
    norm=0.75,
    use_segmentation=True
)
bm25_hier = BM25(
    name="BM25_hi",
    corpus= corpus_hier,
    top_k=5000,     # vì top-K này dựa trên bản Articles bị chunk (mảnh) rồi. Nên để top_k lớn hơn ít nhất 6-10 lần số lượng cần lấy, để đảm bảo đúng ranking.
    norm=0.25,
    use_segmentation=True
)

In [4]:
from sentence_transformers import SentenceTransformer
from src.recall_retriever import Dense
import torch

dense_model = SentenceTransformer(
    "keepitreal/vietnamese-sbert",
    token=os.environ.get("HF_TOKEN"),
    model_kwargs={"torch_dtype": torch.float16},
    device="cuda" 
)
print(f"[SUCCESS] Dense Model sẵn sàng trên: {dense_model.device}")


dense_raw = Dense(
    corpus_simple, dense_model,
    batch_size=8,
    top_k = 200, 
    M=32, ef_construction=512, ef_search=256,
    index_type='Flat', name='DENSE_ra' 
)


dense_hier = Dense(
    corpus_hier, dense_model,
    batch_size=2,
    top_k = 5000, 
    M=256, ef_construction=4096, ef_search=2048,
    index_type='HNSW', name='DENSE_hi' 
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[SUCCESS] Dense Model sẵn sàng trên: cuda:0

In [5]:
from sentence_transformers import CrossEncoder
from src.precision_retriever import CrossEncoderReranker

reranker_model = CrossEncoder(
    "BAAI/bge-reranker-v2-m3", 
    model_kwargs={"torch_dtype": torch.float16},
    device="cuda" 
)
print(f"[SUCCESS] Cross-Encoder sẵn sàng trên: {reranker_model.model.device}")

# Khởi tạo class
crossEncoder = CrossEncoderReranker(
    model=reranker_model,
    name="CE",
    batch_size=8
)

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

[SUCCESS] Cross-Encoder sẵn sàng trên: cuda:0

In [6]:
from src.retrieval_pipeline import RetrievalPipeline


retriever = RetrievalPipeline(
    data = df['content_text'],
    recallLayers=[dense_hier, bm25_hier],
    precisionLayers=[crossEncoder],
    save_folder="saved_model/phapdien"
)

[INFO] Đang build Corpuses
[INFO] [1/1] Đang build <class 'src.data_presentation.HierarchicalCorpus'>
[INFO] Đang load saved models cho lớp Recall Retrievers
[INFO] [1/2] Đang load <class 'src.recall_retriever.Dense'>
[INFO] [1/2] Đang load <class 'src.recall_retriever.BM25'>

# 2. Manual Evaluation

In [7]:
score = retriever.retrieve("Công ty sản xuất nhỏ và vừa tham gia chuỗi giá trị sẽ được hỗ trợ những nội dung gì?")

score_board = pd.concat([df[['docs_code', 'article_index']], score], axis=1)

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
score_board.sort_values(by="BM25_hi_score", ascending=False).head(16)

,docs_code,article_index,DENSE_hi_score,DENSE_hi_comment,BM25_hi_score,BM25_hi_comment,RRF_score,CE_score
8992,80/2021/NĐ-CP,Điều 26,0.599985,[3],17.234537,[1],0.028739,0.984863
8671,80/2021/NĐ-CP,Điều 1,0.694603,[],16.996542,[],0.032522,0.905762
8985,04/2017/QH14,Điều 19,0.670655,"[1, 1]",15.848157,"[2, 4]",0.031746,0.998047
23405,58/2024/NĐ-CP,Điều 24,0.684530,[],15.831905,[],0.031754,0.966797
9008,39/2019/NĐ-CP,Điều 16,0.618677,"[1, 1]",14.179266,"[3, 2]",0.029083,0.941895
8736,80/2021/NĐ-CP,Điều 32,0.602238,"[3, 4]",14.106615,"[3, 1]",0.027652,0.874512
8718,80/2021/NĐ-CP,Điều 4,0.654377,[4],13.835903,[4],0.030550,0.983398
9086,80/2021/NĐ-CP,Điều 28,0.551922,"[1, 5]",13.229777,"[1, 5]",0.022282,0.779785
8988,80/2021/NĐ-CP,Điều 24,0.620056,"[2, 1]",12.785608,"[2, 3]",0.028577,0.985352
8993,80/2021/NĐ-CP,Điều 27,0.547331,[2],12.717123,[2],0.021480,0.913574
8915,55/2019/NĐ-CP,Điều 9,0.469584,"[3, 4]",11.772307,"[3, 4]",0.016460,0.422607
8929,80/2021/NĐ-CP,Điều 13,0.540831,"[2, 1]",11.513651,"[2, 3]",0.020341,0.177246
8918,55/2019/NĐ-CP,Điều 12,0.587692,"[3, 3]",11.243547,[4],0.024568,0.029877
8919,55/2019/NĐ-CP,Điều 13,0.569139,"[3, 2]",11.194885,"[3, 1]",0.022523,0.093689
8934,80/2021/NĐ-CP,Điều 14,0.465289,"[3, 1]",10.920711,[4],0.015503,0.108215
8696,52/2023/TT-BTC,Điều 1,0.551709,[1],10.836029,[1],0.020677,0.932617

In [9]:
score_board.sort_values(by="DENSE_hi_score", ascending=False).head(16)

,docs_code,article_index,DENSE_hi_score,DENSE_hi_comment,BM25_hi_score,BM25_hi_comment,RRF_score,CE_score
8671,80/2021/NĐ-CP,Điều 1,0.694603,[],16.996542,[],0.032522,0.905762
23405,58/2024/NĐ-CP,Điều 24,0.684530,[],15.831905,[],0.031754,0.966797
8985,04/2017/QH14,Điều 19,0.670655,"[1, 1]",15.848157,"[2, 4]",0.031746,0.998047
8718,80/2021/NĐ-CP,Điều 4,0.654377,[4],13.835903,[4],0.030550,0.983398
8989,06/2022/TT-BKHĐT,Điều 17,0.636427,"[1, 3]",7.429907,"[1, 3]",0.022007,0.198730
9095,04/2017/QH14,Điều 27,0.635998,[1],9.295351,[1],0.025253,0.068909
8908,04/2017/QH14,Điều 13,0.635604,"[2, 1]",10.116553,"[2, 2]",0.026161,0.773926
9093,80/2021/NĐ-CP,Điều 30,0.630088,[4],10.549658,[3],0.027206,0.110657
8690,07/2020/TT-BKHCN,Điều 1,0.629403,[],10.654466,[],0.027480,0.015076
9097,04/2017/QH14,Điều 29,0.623783,[1],9.927971,"[2, 2]",0.025397,0.231323
8988,80/2021/NĐ-CP,Điều 24,0.620056,"[2, 1]",12.785608,"[2, 3]",0.028577,0.985352
8949,80/2021/NĐ-CP,Điều 20,0.619008,[3],9.797529,[2],0.024878,0.030853
9008,39/2019/NĐ-CP,Điều 16,0.618677,"[1, 1]",14.179266,"[3, 2]",0.029083,0.941895
8987,06/2022/TT-BKHĐT,Điều 16,0.613262,"[2, 3]",NaN,[],0.013514,0.001028
8920,55/2019/NĐ-CP,Điều 14,0.611357,"[7, 1]",9.081165,"[3, 2]",0.022767,0.022766
8910,55/2019/NĐ-CP,Điều 4,0.610979,"[4, 2]",9.712259,[5],0.023575,0.115173

In [10]:
score_board.sort_values(by="RRF_score", ascending=False).head(16)

,docs_code,article_index,DENSE_hi_score,DENSE_hi_comment,BM25_hi_score,BM25_hi_comment,RRF_score,CE_score
8671,80/2021/NĐ-CP,Điều 1,0.694603,[],16.996542,[],0.032522,0.905762
23405,58/2024/NĐ-CP,Điều 24,0.684530,[],15.831905,[],0.031754,0.966797
8985,04/2017/QH14,Điều 19,0.670655,"[1, 1]",15.848157,"[2, 4]",0.031746,0.998047
8718,80/2021/NĐ-CP,Điều 4,0.654377,[4],13.835903,[4],0.030550,0.983398
9008,39/2019/NĐ-CP,Điều 16,0.618677,"[1, 1]",14.179266,"[3, 2]",0.029083,0.941895
8992,80/2021/NĐ-CP,Điều 26,0.599985,[3],17.234537,[1],0.028739,0.984863
8988,80/2021/NĐ-CP,Điều 24,0.620056,"[2, 1]",12.785608,"[2, 3]",0.028577,0.985352
8736,80/2021/NĐ-CP,Điều 32,0.602238,"[3, 4]",14.106615,"[3, 1]",0.027652,0.874512
8690,07/2020/TT-BKHCN,Điều 1,0.629403,[],10.654466,[],0.027480,0.015076
9093,80/2021/NĐ-CP,Điều 30,0.630088,[4],10.549658,[3],0.027206,0.110657
8908,04/2017/QH14,Điều 13,0.635604,"[2, 1]",10.116553,"[2, 2]",0.026161,0.773926
9097,04/2017/QH14,Điều 29,0.623783,[1],9.927971,"[2, 2]",0.025397,0.231323
9095,04/2017/QH14,Điều 27,0.635998,[1],9.295351,[1],0.025253,0.068909
8949,80/2021/NĐ-CP,Điều 20,0.619008,[3],9.797529,[2],0.024878,0.030853
8950,80/2021/NĐ-CP,Điều 21,0.596114,"[3, 2]",10.613852,"[3, 3]",0.024869,0.038452
8918,55/2019/NĐ-CP,Điều 12,0.587692,"[3, 3]",11.243547,[4],0.024568,0.029877

In [11]:
final = score_board.sort_values(by="CE_score", ascending=False).head(100)
final.to_csv("trash/results_good/bge_results.csv")
final.head(10)

,docs_code,article_index,DENSE_hi_score,DENSE_hi_comment,BM25_hi_score,BM25_hi_comment,RRF_score,CE_score
8985,04/2017/QH14,Điều 19,0.670655,"[1, 1]",15.848157,"[2, 4]",0.031746,0.998047
8988,80/2021/NĐ-CP,Điều 24,0.620056,"[2, 1]",12.785608,"[2, 3]",0.028577,0.985352
8992,80/2021/NĐ-CP,Điều 26,0.599985,[3],17.234537,[1],0.028739,0.984863
8718,80/2021/NĐ-CP,Điều 4,0.654377,[4],13.835903,[4],0.030550,0.983398
23405,58/2024/NĐ-CP,Điều 24,0.684530,[],15.831905,[],0.031754,0.966797
9008,39/2019/NĐ-CP,Điều 16,0.618677,"[1, 1]",14.179266,"[3, 2]",0.029083,0.941895
8696,52/2023/TT-BTC,Điều 1,0.551709,[1],10.836029,[1],0.020677,0.932617
8993,80/2021/NĐ-CP,Điều 27,0.547331,[2],12.717123,[2],0.021480,0.913574
8671,80/2021/NĐ-CP,Điều 1,0.694603,[],16.996542,[],0.032522,0.905762
8991,06/2022/TT-BKHĐT,Điều 18,0.578756,[1],9.763990,[2],0.020753,0.895508

# 4. Retrieval full power

In [13]:
import os       # Thêm thư viện os
import json
import copy
from contextlib import ExitStack

data = 'data/qa/R2AIStage1DATA.json'
result_path = 'results/runs'

# 1. Đọc dữ liệu một lần duy nhất (Load vào bộ nhớ)
try:
    with open(data, 'r', encoding='utf-8') as f_in:
        data = json.load(f_in)
        
        if isinstance(data, dict):
            data = [data]
except FileNotFoundError:
    print(f"Không tìm thấy file")
    data = []


# ==================== CẤU HÌNH TẠI ĐÂY ====================
TOP_K_LIST = [3, 4, 5, 10, 20, 50, 100]
SCORE_COLUMNS = {
    # "bm25_raw": "BM25_ra_score",
    "bm25_hier": "BM25_hi_score",
    "rrf": "RRF_score",
    # "dense_raw": "DENSE_ra_score",
    "dense_hier": "DENSE_hi_score",
    "CrossEncoder": "CE_score"
}
# Cấu hình danh sách các ngưỡng Threshold cho Cross Encoder
CE_THRESHOLDS = [0.8, 0.85, 0.9]
# ==========================================================

# 2. TẠO THƯ MỤC TRƯỚC KHI LƯU FILE
os.makedirs(f"{result_path}/submit", exist_ok=True)
os.makedirs(f"{result_path}/index", exist_ok=True)

with ExitStack() as stack:

    # File handlers cho file chính (chứa relevant_docs, relevant_articles)
    file_handlers_main = {
        metric: {
            k: stack.enter_context(
                open(
                    f"{result_path}/submit/{metric}_top{k}.jsonl",
                    "a",
                    encoding="utf-8"
                )
            )
            for k in TOP_K_LIST
        }
        for metric in SCORE_COLUMNS
    }

    # File handlers cho file index bổ sung (chứa articles_loc)
    file_handlers_index = {
        metric: {
            k: stack.enter_context(
                open(
                    f"{result_path}/index/{metric}_top{k}_index.jsonl",
                    "a",
                    encoding="utf-8"
                )
            )
            for k in TOP_K_LIST
        }
        for metric in SCORE_COLUMNS
    }

    # ================= BỔ SUNG: FILE HANDLERS CHO LIST NGƯỠNG CE =================
    file_handlers_ce_submit = {
        thresh: stack.enter_context(
            open(f"{result_path}/submit/CrossEncoder_threshold{thresh}.jsonl", "a", encoding="utf-8")
        )
        for thresh in CE_THRESHOLDS
    }
    
    file_handlers_ce_index = {
        thresh: stack.enter_context(
            open(f"{result_path}/index/CrossEncoder_threshold{thresh}_index.jsonl", "a", encoding="utf-8")
        )
        for thresh in CE_THRESHOLDS
    }
    # =============================================================================

    for idx, item in enumerate(data):
        if (idx < 950) or (idx >= 1200) : continue
        # if (idx < 1874) : continue

        query = item["question"]
        print(f"Start [{idx}/{len(data)}]: {query}")

        score = retriever.retrieve(query)

        for metric, column in SCORE_COLUMNS.items():
            sorted_score = score.sort_values(
                column,
                ascending=False
            )

            for k in TOP_K_LIST:
                top_k_idx = sorted_score.head(k).index
                articles_df = df.loc[top_k_idx]

                # --- XỬ LÝ CHO FILE CHÍNH ---
                item_main = copy.deepcopy(item)
                item_main["answer"] = ""

                item_main["relevant_docs"] = (
                    (articles_df["docs_code"] + "|" + articles_df["docs_title"])
                    .unique()
                    .tolist()
                )

                item_main["relevant_articles"] = (
                    (articles_df["docs_code"] + "|" + articles_df["docs_title"] + "|" + articles_df["article_index"])
                    .tolist()
                )

                # --- GHI VÀO FILE CHÍNH ---
                f_out_main = file_handlers_main[metric][k]
                json_str_main = json.dumps(
                    item_main,
                    ensure_ascii=False
                )
                f_out_main.write(json_str_main + "\n")
                f_out_main.flush()
                
                # --- XỬ LÝ CHO FILE INDEX ---
                item_index = copy.deepcopy(item)
                item_index['articles_loc'] = top_k_idx.tolist()

                # --- GHI VÀO FILE INDEX ---
                f_out_index = file_handlers_index[metric][k]
                json_str_index = json.dumps(
                    item_index,
                    ensure_ascii=False
                )
                f_out_index.write(json_str_index + "\n")
                f_out_index.flush()

        # ================= BỔ SUNG: XỬ LÝ LƯU THEO LIST NGƯỠNG CE =================
        if "CrossEncoder" in SCORE_COLUMNS:
            ce_col = SCORE_COLUMNS["CrossEncoder"]
            # Sắp xếp theo CE_score giảm dần một lần duy nhất
            ce_sorted = score.sort_values(ce_col, ascending=False)
            
            # Lặp qua từng ngưỡng trong list
            for thresh in CE_THRESHOLDS:
                # Lọc lấy những index có điểm CE > threshold hiện tại
                threshold_mask = ce_sorted[ce_col] > thresh
                ce_threshold_idx = ce_sorted[threshold_mask].index

                articles_ce_df = df.loc[ce_threshold_idx]

                # --- Ghi vào file Submit Threshold ---
                item_ce_submit = copy.deepcopy(item)
                item_ce_submit["answer"] = ""
                item_ce_submit["relevant_docs"] = (articles_ce_df["docs_code"] + "|" + articles_ce_df["docs_title"]).unique().tolist()
                item_ce_submit["relevant_articles"] = (articles_ce_df["docs_code"] + "|" + articles_ce_df["docs_title"] + "|" + articles_ce_df["article_index"]).tolist()
                
                f_out_ce_submit = file_handlers_ce_submit[thresh]
                f_out_ce_submit.write(json.dumps(item_ce_submit, ensure_ascii=False) + "\n")
                f_out_ce_submit.flush()

                # --- Ghi vào file Index Threshold ---
                item_ce_index = copy.deepcopy(item)
                item_ce_index['articles_loc'] = ce_threshold_idx.tolist()
                
                f_out_ce_index = file_handlers_ce_index[thresh]
                f_out_ce_index.write(json.dumps(item_ce_index, ensure_ascii=False) + "\n")
                f_out_ce_index.flush()
        # ==========================================================================

        print("Đã hoàn tất quá trình cập nhật và lưu file!")

Start [950/2000]: Công ty muốn thuê một chuyên gia cao tuổi làm công việc độc hại, đồng thời có nhân viên nữ đang nuôi con dưới 12 tháng tuổi nhưng không cho nghỉ 60 phút mỗi ngày thì điều kiện tuyển dụng chuyên gia này là gì và công ty sẽ bị xử lý ra sao đối với trường hợp nhân viên nữ?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [951/2000]: Trong trường hợp hợp đồng lao động bị tuyên bố vô hiệu toàn bộ dẫn đến doanh nghiệp cho thuê lại không đủ khả năng bồi thường cho người lao động, công ty cần làm gì để sử dụng tiền ký quỹ chi trả và quy trình rút số tiền này thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [952/2000]: Công ty nhập khẩu và phân phối một lô hàng bị lỗi gây thiệt hại cho khách hàng, trong khi hợp đồng với nhà cung cấp có điều khoản phạt vi phạm, thì công ty phải bồi thường những gì cho khách hàng và có quyền yêu cầu nhà cung cấp trả khoản tiền nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [953/2000]: Công ty tôi muốn đăng ký nhận các gói hỗ trợ cho doanh nghiệp nhỏ và vừa, vậy làm sao để xác định chính xác công ty thuộc nhóm siêu nhỏ, nhỏ hay vừa dựa trên quy mô vốn, doanh thu, lao động và lĩnh vực hoạt động?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [954/2000]: Khi một thỏa ước lao động tập thể ngành được cơ quan nhà nước quyết định mở rộng áp dụng cho công ty tôi, nếu công ty từ chối thương lượng tập thể, không bố trí địa điểm họp và không cung cấp thông tin sản xuất kinh doanh theo yêu cầu thì sẽ bị xử lý như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [955/2000]: Công ty yêu cầu 20 nhân viên làm thêm giờ vào ngày lễ mà không được họ đồng ý, đồng thời yêu cầu họ tham gia tập huấn chuyên môn trong thời gian này thì mức lương phải trả tính thế nào và rủi ro bị xử phạt ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [956/2000]: Nhân viên của công ty tự ý ký thỏa thuận trọng tài bằng email với khách hàng cá nhân nhưng vượt quá thẩm quyền đại diện, vậy thỏa thuận này có hiệu lực về hình thức không và công ty phải xử lý hậu quả pháp lý cũng như tranh chấp này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [957/2000]: Nếu công ty triển khai hệ thống AI nhưng vô tình để xảy ra sự cố nghiêm trọng gây tổn hại dữ liệu khách hàng và bị nghi ngờ cố tình che giấu thông tin cảnh báo, công ty cần xử lý sự cố này như thế nào và rủi ro pháp lý về hành vi bị nghiêm cấm là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [958/2000]: Tại một đơn vị không được đình công, nếu các bên đồng thuận yêu cầu Hội đồng trọng tài lao động giải quyết tranh chấp về lợi ích nhưng công ty không thực hiện quyết định của Ban trọng tài và kỷ luật nhân viên tham gia khiếu nại thì quy trình xử lý tiếp theo là gì và công ty đối mặt với rủi ro pháp lý nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [959/2000]: Công ty tôi đang thuê lại lao động từ một đối tác nhưng phát hiện đối tác này vừa bị thu hồi giấy phép hoạt động, vậy công ty tôi có bị xử lý vi phạm gì không và đối tác đó phải giải quyết hậu quả như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [960/2000]: Một nhân viên nữ mang thai có xác nhận của bệnh viện về việc tiếp tục làm việc sẽ ảnh hưởng xấu tới thai nhi nên muốn tạm hoãn hợp đồng, đồng thời cô ấy phản ánh công ty không cho nghỉ 30 phút mỗi ngày trong thời gian hành kinh thì công ty phải xử lý yêu cầu tạm hoãn này thế nào và rủi ro pháp lý đối với việc không cho nghỉ hành kinh là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [961/2000]: Công ty tôi đang bị một đối thủ cạnh tranh sử dụng tên thương mại tương tự, đồng thời sao chép kiểu dáng công nghiệp của sản phẩm và dùng nhãn hiệu gây nhầm lẫn, vậy tôi cần căn cứ vào những yếu tố nào để xác định các hành vi này là xâm phạm quyền sở hữu trí tuệ?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [962/2000]: Công ty muốn tổ chức đối thoại với nhân viên về tình hình sản xuất kinh doanh và điều kiện làm việc thì cần thực hiện trách nhiệm tổ chức như thế nào và nếu không công khai nội dung đối thoại thì rủi ro pháp lý là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [963/2000]: Công ty đã ra thông báo đơn phương chấm dứt hợp đồng với nhân viên làm việc 5 năm nhưng nay muốn hủy bỏ quyết định này thì phải thực hiện thế nào, và nếu không hủy mà cho thôi việc thì những trường hợp chấm dứt nào sẽ phát sinh trách nhiệm chi trả trợ cấp thôi việc?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [964/2000]: Công ty tôi muốn đăng ký bảo hộ cho cả kiểu dáng công nghiệp của sản phẩm và chỉ dẫn địa lý cho đặc sản vùng miền thì quy trình thẩm định hình thức của chỉ dẫn địa lý được thực hiện thế nào và sau khi được cấp văn bằng thì những thông tin nào của hai đối tượng này sẽ được công bố trên Công báo?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [965/2000]: Công ty muốn thuê chuyên gia nước ngoài làm việc tại Việt Nam thì cần đảm bảo những điều kiện gì về nhân thân, thủ tục cấp phép và rủi ro xử phạt ra sao nếu sử dụng lao động khi giấy phép đã hết hạn?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [966/2000]: Khi công ty đang nộp đơn đăng ký sở hữu công nghiệp, nếu có người thứ ba phản đối việc cấp văn bằng hoặc yêu cầu hủy bỏ hiệu lực văn bằng sau khi đã cấp thì quy trình xử lý và hồ sơ yêu cầu hủy bỏ được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [967/2000]: Công ty muốn chuyển nhượng quyền sở hữu tác phẩm cho đối tác, đồng thời muốn sửa đổi nội dung hợp đồng chuyển quyền sử dụng sáng chế đã đăng ký và tìm hiểu về thủ tục yêu cầu bắt buộc chuyển giao quyền sử dụng sáng chế thì phải thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [968/2000]: Khi phát hiện một đối thủ sao chép trái phép phần mềm của công ty để bán ra thị trường, công ty cần xác định hành vi này có phải là xâm phạm quyền tác giả không và cách tính toán mức giảm sút thu nhập cùng tổn thất cơ hội kinh doanh trong trường hợp này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [969/2000]: Công ty tôi đang nhận quyền thương mại và thuê thiết bị từ bên nhượng quyền, nhưng nay bên nhượng quyền chuyển nhượng quyền sở hữu thiết bị này cho bên thứ ba và xảy ra sự cố bất khả kháng khiến công ty tôi không thể thực hiện nghĩa vụ thanh toán, vậy hiệu lực hợp đồng thuê thiết bị thay đổi ra sao và công ty tôi cần xử lý thông báo thế nào để được miễn trách nhiệm?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [970/2000]: Đối tác giao hàng thiếu và kém chất lượng, công ty muốn yêu cầu họ giao bù, khắc phục lỗi đồng thời đòi tiền phạt vi phạm và bồi thường thiệt hại thì cách áp dụng các chế tài này cùng lúc như thế nào cho đúng luật?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [971/2000]: Công ty tôi là một tổ chức kinh tế có đăng ký kinh doanh, hiện đang thuê máy móc từ một đối tác; vậy công ty có quyền từ chối nhận hàng trong trường hợp nào và sau khi nhận hàng thì có những nghĩa vụ cơ bản gì đối với tài sản thuê này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [972/2000]: Công ty tôi là doanh nghiệp siêu nhỏ mới thành lập vào tháng 10, vậy cách xác định kỳ kế toán năm đầu tiên và những thông tin chung nào bắt buộc phải trình bày trong báo cáo tài chính năm theo chế độ kế toán đơn giản là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [973/2000]: Công ty tôi thuộc diện được hưởng ưu đãi thuế suất và thời gian miễn thuế thu nhập doanh nghiệp thì quy trình nộp hồ sơ, thành phần hồ sơ cần chuẩn bị và cơ quan nào có thẩm quyền quyết định việc miễn giảm này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [974/2000]: Công ty tôi nhận chuyển nhượng quyền đối với giống cây trồng từ một đơn vị khác, nhưng hiện đang bị tác giả của giống cây đó khiếu nại về mức thù lao và bị yêu cầu giám định xâm phạm, vậy công ty cần thực hiện thủ tục chuyển nhượng thế nào cho đúng và quy trình yêu cầu giám định cũng như nghĩa vụ trả thù lao cho tác giả được xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [975/2000]: Để nâng cao năng lực sản xuất, công ty muốn tiếp cận các hoạt động hỗ trợ tăng cường năng lực, đồng thời tìm hiểu về việc tài trợ chi phí mua máy móc và quy định về hợp đồng khi vay vốn gián tiếp từ Quỹ phát triển doanh nghiệp nhỏ và vừa thì cần lưu ý những nội dung gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [976/2000]: Công ty tôi đang làm thủ tục giải thể và có nợ thuế nên muốn xin gia hạn nộp thuế đồng thời đề nghị hoàn một khoản thuế thừa, vậy quy trình tiếp nhận hồ sơ gia hạn nộp thuế diễn ra thế nào và hồ sơ hoàn thuế của công ty sẽ được phân loại ra sao, ai là người chịu trách nhiệm với số thuế nợ còn lại?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [977/2000]: Công ty có nhân viên làm việc không trọn thời gian vừa hết thời hạn tạm hoãn hợp đồng nhưng hiện đang nuôi con dưới 12 tháng tuổi thì công ty phải xử lý việc nhận lại và quyền đơn phương chấm dứt hợp đồng với nhân viên này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [978/2000]: Công ty muốn tuyển một quản lý doanh nghiệp thông qua người được ủy quyền ký hợp đồng, yêu cầu thử việc 200 ngày và yêu cầu nộp bằng đại học bản chính để đối chiếu giữ lại thì cách làm này có đúng quy định không và cần điều chỉnh những điểm nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [979/2000]: Khi một quỹ đầu tư khởi nghiệp sáng tạo muốn phân chia lợi tức cho nhà đầu tư nước ngoài, công ty quản lý quỹ cần tuân thủ những điều kiện chi trả nào, thời hạn thông báo ra sao và việc chuyển lợi nhuận này ra nước ngoài được thực hiện theo quy định nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [980/2000]: Công ty phát hiện đối tác vi phạm hợp đồng từ 3 năm trước nhưng giờ mới muốn khởi kiện trọng tài, vậy công ty cần xử lý về thời hiệu ra sao và nếu muốn xác lập thỏa thuận trọng tài thông qua bản tự bảo vệ thì nội dung bản này cần có gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [981/2000]: Công ty tôi vừa bị phát hiện kinh doanh hàng giả mạo sở hữu trí tuệ, đồng thời bị thanh tra phát hiện chưa từng tiến hành quan trắc môi trường lao động và không xây dựng quy chế dân chủ ở cơ sở thì sẽ bị xử lý và áp dụng các biện pháp khắc phục hậu quả như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [982/2000]: Công ty đang giải quyết tranh chấp bằng trọng tài và có áp dụng biện pháp khẩn cấp tạm thời, nhưng nay muốn hủy bỏ biện pháp này trong khi đối tác lại khiếu nại lên Tòa án về việc thỏa thuận trọng tài qua email là vô hiệu thì công ty phải xử lý các thủ tục này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [983/2000]: Công ty cổ phần muốn bổ sung thêm một người đại diện theo pháp luật thứ hai thì cần quy định những nội dung gì trong Điều lệ và thông tin nào của người này phải hiển thị trên Giấy chứng nhận đăng ký doanh nghiệp?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [984/2000]: Công ty TNHH hai thành viên muốn bổ nhiệm Kiểm soát viên nhưng người đại diện theo pháp luật hiện tại đang ở nước ngoài không thể ký văn bản, thì Hội đồng thành viên cần tổ chức họp với điều kiện tỷ lệ vốn bao nhiêu và quy trình cử người đại diện mới để thực hiện thủ tục này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [985/2000]: Công ty muốn thành lập chi nhánh để thực hiện chức năng kinh doanh, đồng thời tiếp nhận một mảnh đất góp vốn từ cổ đông và giao cho người đại diện theo pháp luật ký biên bản bàn giao thì quy trình chuyển quyền sở hữu tài sản này và vai trò của người đại diện trong việc ký kết biên bản được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [986/2000]: Một thành viên Hội đồng quản trị muốn yêu cầu Tổng giám đốc cung cấp báo cáo tài chính để chuẩn bị nội dung đề nghị triệu tập họp Hội đồng quản trị bất thường thì quy trình yêu cầu thông tin này thực hiện thế nào và ai là người có thẩm quyền triệu tập cuộc họp nếu Chủ tịch không thực hiện?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [987/2000]: Công ty tôi đang nợ Quỹ bảo lãnh tín dụng sau khi Quỹ đã thực hiện nghĩa vụ bảo lãnh, nay do khó khăn trong sản xuất kinh doanh nên muốn xin điều chỉnh kỳ hạn trả nợ thì cần đáp ứng điều kiện gì và thời điểm nào Quỹ sẽ xem xét xử lý rủi ro này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [988/2000]: Công ty muốn nộp đơn PCT có nguồn gốc Việt Nam nhưng sau đó muốn tách đơn hoặc rút đơn thì quy trình xử lý tại cơ quan quản lý nhà nước diễn ra thế nào và nếu quá hạn nộp tài liệu sửa đổi do sự kiện bất khả kháng thì xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [989/2000]: Công ty muốn thu hẹp phạm vi bảo hộ của nhãn hiệu, đồng thời thực hiện gia hạn hiệu lực cho bằng độc quyền sáng chế và thay đổi địa chỉ trụ sở trên văn bằng thì phải làm thủ tục như thế nào và phạm vi quyền sở hữu công nghiệp sau đó được xác định ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [990/2000]: Một hộ kinh doanh vừa chuyển đổi thành doanh nghiệp nhỏ và vừa khởi nghiệp sáng tạo, có tiềm năng cung ứng cho doanh nghiệp đầu chuỗi thì sẽ được hỗ trợ những gì về thủ tục thuế, kế toán, các chi phí vận hành sáng tạo và điều kiện để được chọn tham gia chuỗi giá trị?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [991/2000]: Nhân viên công ty bị tai nạn khi đang đi công tác theo yêu cầu của sếp hoặc bị tai nạn trên đường từ nhà đến công ty, nếu công ty chưa đóng bảo hiểm tai nạn lao động bắt buộc thì cách xử lý bồi thường, chi trả chế độ và nghĩa vụ báo cáo về bệnh nghề nghiệp hằng năm của công ty được thực hiện thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [992/2000]: Đối với những người học nghề, tập nghề làm công việc nặng nhọc, độc hại, nguy hiểm tại công ty thì quy định về tần suất khám sức khỏe hằng năm và chế độ điều dưỡng phục hồi sức khỏe được áp dụng như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [993/2000]: Khi công ty hỗ trợ nhân viên đăng ký lao động để họ được đánh giá cấp chứng chỉ kỹ năng nghề quốc gia, công ty cần thu thập những nhóm thông tin gì và nhân viên có nghĩa vụ gì đối với các thông tin này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [994/2000]: Khi công ty lập hóa đơn để ghi nhận doanh thu nhưng lại thỏa thuận với khách hàng để khai man số liệu và không lưu trữ chứng từ này theo trình tự thời gian thì việc làm này vi phạm điều cấm nào và ảnh hưởng thế nào đến căn cứ ghi sổ kế toán?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [995/2000]: Công ty cho đối tác vay vốn có bảo đảm bằng tín chấp qua tổ chức chính trị - xã hội, nhưng đến hạn đối tác không trả nợ thì công ty thực hiện cầm giữ tài sản của họ như thế nào để đảm bảo đúng chuẩn mực pháp lý về quan hệ dân sự?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [996/2000]: Công ty tôi muốn tìm hiểu về việc giải quyết vướng mắc pháp lý chung và thuê tư vấn viên cho vụ việc cụ thể thì quy trình thực hiện, mức hỗ trợ chi phí và thời hạn của chương trình hỗ trợ pháp lý này được quy định thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [997/2000]: Công ty muốn cùng một đối tác đóng góp vốn và công sức để khai thác mảnh đất thuê, nhưng không rõ nên lập hợp đồng hợp tác, hợp đồng dịch vụ hay hợp đồng về quyền sử dụng đất thì loại nào phù hợp với đặc điểm của từng hình thức này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [998/2000]: Công ty ủy quyền cho một cá nhân ký kết hợp đồng với đối tác, nhưng người này ký khi thời hạn ủy quyền đã hết và ký vượt quá phạm vi được giao thì hợp đồng đó có làm phát sinh nghĩa vụ cho công ty không và cách xác định thời hạn, phạm vi đại diện trong trường hợp này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [999/2000]: Đối tác chậm giao hàng khiến công ty không đạt được mục đích kinh doanh, công ty muốn chấm dứt hợp đồng thì nên chọn phương án hủy bỏ hay đơn phương chấm dứt để xử lý việc hoàn trả tài sản và bồi thường thiệt hại như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1000/2000]: Khi công ty chuyển đổi loại hình doanh nghiệp, để đảm bảo tài sản an toàn và báo cáo tài chính trung thực trước khi bàn giao, công ty cần thực hiện những công việc kế toán nào và nếu có đoàn kiểm tra kế toán vào thời điểm này thì họ có quyền hạn gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1001/2000]: Công ty cho đối tác thuê máy móc và yêu cầu dùng chính máy móc đó làm tài sản bảo đảm cho khoản thanh toán, nếu đối tác không giao máy để xử lý khi vi phạm thì công ty cần đáp ứng điều kiện gì về quyền sở hữu, hiệu lực đối kháng và cách xử lý để thu hồi tài sản?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1002/2000]: Công ty ký hợp đồng bằng văn bản với một đối tác nhưng nội dung điều khoản không rõ ràng, đồng thời sau đó phát hiện đối tác là người bị hạn chế năng lực hành vi dân sự thì việc giải thích nội dung hợp đồng và xác định hiệu lực của giao dịch này được xử lý như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1003/2000]: Doanh nghiệp tôi vừa gặp hỏa hoạn gây thiệt hại nặng nề cho cả nhà xưởng, đất sản xuất phi nông nghiệp và đất nông nghiệp, đồng thời ảnh hưởng đến hàng hóa chịu thuế tiêu thụ đặc biệt thì cần chuẩn bị những loại hồ sơ gì để đề nghị miễn, giảm các khoản thuế này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1004/2000]: Khi thuê đơn vị vận chuyển hàng hóa, công ty cần thực hiện những nghĩa vụ gì về thanh toán, thông tin tài sản và có quyền yêu cầu hay xử lý thế nào nếu bên vận chuyển giao hàng sai địa điểm hoặc làm hư hỏng hàng hóa?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1005/2000]: Công ty tôi thuê một đơn vị phần mềm quản lý dữ liệu khách hàng, vậy công ty cần xây dựng quy tắc bảo vệ thông tin gồm những nội dung gì, việc thuê bên thứ ba này phải đáp ứng điều kiện nào và khi khách hàng yêu cầu xóa dữ liệu thì công ty phải xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1006/2000]: Công ty tôi đang làm đại lý thương mại và đồng thời cung cấp dịch vụ logistics, nếu hiện nay công ty muốn mở rộng sang nhượng quyền thương mại thì cần đăng ký với cơ quan nào, và trong trường hợp công ty cầm giữ hàng hóa của bên giao đại lý thì phải thực hiện những nghĩa vụ gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1007/2000]: Công ty muốn chạy chiến dịch khuyến mại cho sản phẩm mới thông qua một đơn vị quảng cáo chuyên nghiệp thì cần thực hiện những nghĩa vụ gì về thủ tục khuyến mại và có những quyền hạn nào khi thuê dịch vụ quảng cáo này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1008/2000]: Công ty tôi là công ty cổ phần, hiện đang gặp khó khăn trong việc triệu tập họp Đại hội đồng cổ đông do không đủ tỷ lệ dự họp, tôi muốn biết quy trình triệu tập, thời hạn gửi thông báo mời họp cho các lần triệu tập tiếp theo và sự khác biệt về điều kiện tiến hành họp này so với mô hình công ty TNHH hai thành viên trở lên?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1009/2000]: Công ty tôi đáp ứng tiêu chí doanh nghiệp nhỏ và vừa thì được hưởng những quyền lợi gì về chi phí khi sử dụng dịch vụ từ mạng lưới tư vấn viên và tham gia các khóa đào tạo sử dụng ngân sách nhà nước?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1010/2000]: Công ty tôi không thông tin cho nhân viên về các yếu tố nguy hiểm tại nơi làm việc và không trang cấp đầy đủ phương tiện bảo vệ cá nhân thì sẽ bị xử lý như thế nào và phải khắc phục ra sao để tuân thủ đúng pháp luật về an toàn, vệ sinh lao động?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1011/2000]: Công ty tôi soạn sẵn hợp đồng theo mẫu và điều kiện giao dịch chung để khách hàng ký, vậy công ty cần thực hiện công khai các nội dung này thế nào và nếu có điều khoản miễn trách nhiệm cho công ty thì hiệu lực pháp lý sẽ ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1012/2000]: Công ty đơn phương chấm dứt hợp đồng với một cán bộ công đoàn vì lý do người này liên tục yêu cầu công ty thực hiện biện pháp khắc phục nguy hiểm tại nơi làm việc thì hành vi này bị nghiêm cấm ra sao và công ty phải đối mặt với rủi ro xử phạt, khắc phục hậu quả thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1013/2000]: Công ty muốn thuê đơn vị tổ chức trưng bày sản phẩm tại một hội chợ thương mại ở nước ngoài thì cần lập hợp đồng thế nào, bên công ty phải thực hiện những nghĩa vụ gì và việc bán hàng tại đó được xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1014/2000]: Khi doanh nghiệp nhỏ và vừa khởi nghiệp sáng tạo muốn nhận đầu tư từ một quỹ được tổ chức tài chính nhà nước địa phương lựa chọn cùng đầu tư, thì quỹ đó cần đáp ứng điều kiện gì, doanh nghiệp nhận vốn có trách nhiệm gì và nếu quỹ này thay đổi vốn góp thì phải tuân thủ quy định nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1015/2000]: Công ty tôi là đối tượng nộp thuế, hiện đang khiếu nại về một quyết định xử phạt thuế thì cơ quan quản lý thuế có quyền yêu cầu cung cấp hồ sơ gì và nếu kết quả giải quyết cho thấy công ty bị thu sai thì quy trình hoàn trả tiền được thực hiện như thế nào, ai là người có thẩm quyền xử lý khiếu nại này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1016/2000]: Công ty tôi đang nộp đơn đăng ký cho một sản phẩm đặc sản vùng miền và một sáng chế mới, vậy hồ sơ chỉ dẫn địa lý cần những tài liệu gì, làm sao để đơn được coi là hợp lệ và thời hạn yêu cầu thẩm định nội dung sáng chế là bao lâu để không bị coi là rút đơn?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1017/2000]: Khi chuẩn bị thành lập công ty, tôi ký hợp đồng thuê văn phòng và mua thiết bị, vậy tôi cần thực hiện nghĩa vụ đăng ký doanh nghiệp và đăng ký thuế như thế nào, và ai sẽ chịu trách nhiệm với các hợp đồng này nếu công ty không được cấp giấy chứng nhận đăng ký doanh nghiệp?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1018/2000]: Trong trường hợp nhân viên bị chết do tai nạn lao động, nếu công ty không tổ chức điều trị phục hồi chức năng trước đó và hiện tại chậm chi trả trợ cấp cho thân nhân thì sẽ bị xử lý hành chính ra sao và thân nhân người lao động được hưởng những khoản trợ cấp nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1019/2000]: Công ty tôi muốn đồng thời thay đổi tên doanh nghiệp và chuyển trụ sở chính sang tỉnh khác, vậy quy trình thực hiện với cơ quan thuế và cơ quan đăng ký kinh doanh như thế nào, và thời hạn để cập nhật thông tin cho các chi nhánh là bao lâu?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1020/2000]: Khi công ty TNHH hai thành viên trở lên tiếp nhận một tổ chức làm thành viên mới do chuyển nhượng vốn, công ty cần chuẩn bị văn bản cử người đại diện cho tổ chức này với những nội dung gì và hồ sơ đăng ký thay đổi thành viên cần những giấy tờ nào, trong đó trường hợp nào được miễn bản sao giấy tờ pháp lý của cá nhân người đại diện?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1021/2000]: Công ty tôi đang tạm ngừng kinh doanh nhưng nay muốn giải thể hẳn, đồng thời có một chi nhánh đã ngừng hoạt động hơn một năm mà chưa thông báo thì quy trình giải thể công ty và xử lý chi nhánh này phải thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1022/2000]: Khi xảy ra tranh chấp thương mại với khách hàng cá nhân, công ty cần thực hiện các hình thức giải quyết nào và người đại diện của công ty khi tham gia giải quyết phải tuân thủ phạm vi đại diện ra sao, đặc biệt nếu trong hợp đồng mẫu có điều khoản trọng tài?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1023/2000]: Công ty tôi là doanh nghiệp nhỏ và vừa mới chuyển đổi từ hộ kinh doanh, vậy tôi có thể tìm kiếm các thông tin hỗ trợ kinh doanh ở đâu và được hưởng những chính sách miễn, giảm chi phí tư vấn hay hướng dẫn thuế, kế toán cụ thể như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1024/2000]: Công ty đem hàng hóa tham gia triển lãm tại nước ngoài và ký hợp đồng theo mẫu với khách hàng tại đó, vậy việc bán hàng này cần tuân thủ điều kiện gì, công ty phải thực hiện nghĩa vụ công khai hợp đồng ra sao và nếu muốn hủy bỏ hợp đồng thì cần xử lý thế nào để không phải bồi thường?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1025/2000]: Công ty ký hợp đồng thương mại với một cá nhân nhưng sau đó phát hiện người này là người bị hạn chế năng lực hành vi dân sự, vậy công ty cần làm gì để tuyên bố hợp đồng vô hiệu và thời hạn để khởi kiện ra Tòa án hoặc Trọng tài là bao lâu?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1026/2000]: Công ty thỏa thuận trả lương thử việc cho nhân viên theo giờ với mức lương chỉ bằng 80% lương chính thức, nếu bị thanh tra thì mức xử phạt hành chính và cách khắc phục hậu quả về tiền lương được tính như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1027/2000]: Công ty muốn gia nhập một thỏa ước lao động tập thể ngành thì cần điều kiện gì, và nếu trong quá trình thương lượng công ty từ chối yêu cầu hoặc không bố trí địa điểm họp thì sẽ bị xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1028/2000]: Trong khi Ban trọng tài lao động đang giải quyết tranh chấp theo quy trình, nếu công ty đơn phương kỷ luật nhân viên vì lý do tham gia đình công thì hành vi này có vi phạm pháp luật không và công ty sẽ bị xử lý, khắc phục hậu quả ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1029/2000]: Công ty không cho nhân viên nữ nghỉ 30 phút mỗi ngày trong thời gian hành kinh và không đảm bảo điều kiện an toàn vệ sinh lao động cho lao động nữ thì sẽ bị xử lý như thế nào và phải khắc phục ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1030/2000]: Công ty có 15 nhân viên nhưng chưa ban hành nội quy lao động bằng văn bản, nay muốn sa thải một nhân viên vì vi phạm kỷ luật thì rủi ro bị xử phạt hành chính là gì và nhân viên đó có quyền yêu cầu giải quyết như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1031/2000]: Công ty muốn xác lập quyền chủ sở hữu đối với một sáng chế để ngăn cấm đối thủ cạnh tranh sử dụng thì cần thực hiện thủ tục gì và trong trường hợp nào công ty không có quyền cấm đối thủ sử dụng sáng chế đó?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1032/2000]: Công ty phát hiện đối tác tự ý sao chép một phần phần mềm của mình để kinh doanh và quảng cáo thu lợi, vậy hành vi này được xác định là xâm phạm quyền tác giả như thế nào và công ty có thể yêu cầu bồi thường những khoản chi phí, tổn thất cụ thể nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1033/2000]: Công ty tôi muốn đặt tên thương mại cho chuỗi cửa hàng mới, nhưng tên này có chứa một từ dễ gây nhầm lẫn về xuất xứ hàng hóa và trùng với một nhãn hiệu đã bảo hộ, vậy tên này có được coi là có khả năng phân biệt không và nếu tôi vẫn sử dụng trên biển hiệu thì sẽ bị xác định là xâm phạm quyền đối với tên thương mại dựa trên những căn cứ nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1034/2000]: Khi phát hiện lô hàng nhập khẩu sao chép lậu tác phẩm của công ty, công ty cần cung cấp chứng cứ gì để yêu cầu cơ quan hải quan tạm dừng làm thủ tục và các hàng hóa này sẽ bị xử lý như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1035/2000]: Một thành viên công ty TNHH hai thành viên trở lên muốn chuyển nhượng phần vốn góp bằng quyền sở hữu trí tuệ cho người ngoài thì quy trình chào bán thực hiện thế nào và hồ sơ đăng ký thay đổi phần vốn góp cần những giấy tờ gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1036/2000]: Công ty đơn phương chấm dứt hợp đồng trái pháp luật với một nhân viên làm việc 5 năm, nếu nhân viên này không muốn quay lại làm việc thì công ty phải bồi thường những khoản nào và cách xác định thời gian để tính trợ cấp thôi việc cho họ ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1037/2000]: Công ty nhập khẩu một lô hàng chứa các tác phẩm mà Nhà nước là đại diện chủ sở hữu để phục vụ nghiên cứu cá nhân không thương mại thì được miễn phí bản quyền ra sao và nếu bị hải quan nghi ngờ xâm phạm quyền tác giả thì sẽ bị xử lý thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1038/2000]: Công ty tôi đang nộp đơn đăng ký cả kiểu dáng công nghiệp cho bao bì và chỉ dẫn địa lý cho đặc sản vùng miền, vậy quy trình thẩm định nội dung của hai loại đơn này khác nhau thế nào và sau khi được cấp văn bằng thì những thông tin nào sẽ được công bố trên Công báo?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1039/2000]: Khi công ty đang chờ cấp văn bằng bảo hộ nhãn hiệu, nếu có bên thứ ba gửi ý kiến phản đối hoặc cơ quan quản lý thông báo dự định cấp văn bằng thì công ty cần xử lý thế nào và trường hợp nào nhãn hiệu sẽ bị hủy bỏ hiệu lực do dụng ý xấu?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1040/2000]: Công ty muốn nộp đơn đăng ký nhãn hiệu tại Việt Nam và hưởng quyền ưu tiên từ đơn đã nộp tại Pháp, nhưng sau đó bị một bên khác nộp ý kiến phản đối về khả năng phân biệt của nhãn hiệu thì quy trình xử lý và điều kiện hưởng quyền ưu tiên này được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1041/2000]: Công ty tôi nhận quyền thương mại nhưng do sự cố bất khả kháng nên không thể đầu tư đủ cơ sở vật chất và tuân thủ thiết kế theo yêu cầu của bên nhượng quyền, vậy công ty cần xử lý thông báo thế nào để được miễn trách nhiệm và những nghĩa vụ cơ bản nào về vận hành mà công ty vẫn phải đảm bảo?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1042/2000]: Công ty tôi muốn đăng ký bảo hộ đồng thời cho một sáng chế, một kiểu dáng công nghiệp và một nhãn hiệu thì quy trình thẩm định hình thức của sáng chế được thực hiện thế nào, và đơn đăng ký kiểu dáng cũng như nhãn hiệu cần đáp ứng những yêu cầu đặc thù gì để không bị từ chối?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1043/2000]: Trong trường hợp công ty muốn chuyển nhượng quyền tác giả của một phần mềm có đồng chủ sở hữu và đồng thời yêu cầu cơ quan nhà nước ra quyết định bắt buộc chuyển giao quyền sử dụng một sáng chế liên quan, công ty cần thực hiện thủ tục nộp hồ sơ ra sao và hợp đồng chuyển nhượng cần đảm bảo những nội dung chính nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1044/2000]: Công ty nhận chuyển nhượng quyền đối với giống cây trồng từ một đối tác, nhưng hiện đang có tranh chấp về kết luận giám định giống này và chưa thống nhất mức thù lao cho tác giả thì công ty phải xử lý việc giám định lại như thế nào và thực hiện nghĩa vụ tài chính với tác giả ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1045/2000]: Trong trường hợp công ty bị cơ quan thuế ấn định thuế do kê khai không trung thực và dẫn đến chậm nộp tiền thuế, thì số tiền chậm nộp này được tính như thế nào và quy trình thông báo, điều chỉnh giảm số tiền này ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1046/2000]: Công ty tôi là doanh nghiệp siêu nhỏ, muốn thuê một tổ chức kinh doanh dịch vụ làm thủ tục về thuế để thực hiện chế độ kế toán đơn giản và lập Báo cáo tình hình tài chính thì đơn vị đó cần điều kiện gì và báo cáo cần trình bày những thông tin chung nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1047/2000]: Công ty tôi đang tạm ngừng kinh doanh nhưng cần thực hiện giao dịch với nhà cung cấp nước ngoài thì việc sử dụng mã số thuế của công ty, của nhà cung cấp này và quy định về hóa đơn trong thời gian tạm ngừng được xử lý thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1048/2000]: Công ty tôi muốn mời một chuyên gia nước ngoài đủ 18 tuổi, có chuyên môn tốt vào xử lý sự cố kỹ thuật phức tạp trong 2 tháng thì cần đáp ứng điều kiện gì về giấy phép và nếu không làm thủ tục xác nhận thì công ty cùng chuyên gia này sẽ bị xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1049/2000]: Công ty tôi đang bị cưỡng chế thuế và không hoạt động tại địa chỉ đã đăng ký, vậy người đại diện theo pháp luật sẽ bị xử lý về việc xuất cảnh như thế nào và cơ quan thuế căn cứ vào những tiêu chí nào để đánh giá mức độ tuân thủ trong trường hợp này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1050/2000]: Đối tác giao hàng kém chất lượng và chậm tiến độ gây thiệt hại cho công ty, vậy công ty có quyền yêu cầu họ khắc phục hàng hóa, trả tiền phạt vi phạm và bồi thường thiệt hại như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1051/2000]: Công ty tôi là thương nhân thuê máy móc từ một đối tác, sau khi đã kiểm tra và xác nhận nhận hàng thì phát hiện máy không đúng thỏa thuận, vậy công ty có được trả lại hàng không và trong thời gian thuê thì công ty có quyền yêu cầu bảo dưỡng hay tự sửa chữa rồi đòi chi phí như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1052/2000]: Công ty tôi đang làm thủ tục giải thể nhưng vẫn còn nợ thuế và có hồ sơ hoàn thuế đang chờ xử lý, vậy việc nộp nợ thuế còn lại sẽ do ai chịu trách nhiệm và nếu cơ quan thuế chậm ra quyết định hoàn thuế thì công ty được giải quyết quyền lợi thế nào, đồng thời nếu muốn xin gia hạn nộp số thuế nợ này thì quy trình tiếp nhận hồ sơ ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1053/2000]: Khi tuyển dụng nhân sự mới, công ty muốn giao cho Trưởng phòng nhân sự ký hợp đồng thử việc với mức lương 80% lương chính thức và yêu cầu nhân viên nộp bằng đại học bản gốc để lưu giữ thì cách làm này có đúng quy định không và cần điều chỉnh những điểm nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1054/2000]: Công ty tôi đang gặp khó khăn đặc biệt do ngành nghề kinh doanh suy thoái và vừa bị hỏa hoạn gây thiệt hại lớn, vậy tôi cần chuẩn bị hồ sơ gì để xin gia hạn nộp thuế và cơ chế giải quyết cho hai trường hợp này khác nhau như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1055/2000]: Công ty tôi tự tính thuế nhưng nộp tiền vào ngân sách trước khi nộp hồ sơ khai thuế dẫn đến nộp thừa, vậy thời điểm xác định khoản nộp thừa này là khi nào và quy trình bù trừ hoặc hoàn trả số tiền này được thực hiện ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1056/2000]: Khi công ty muốn tiếp cận nguồn vốn từ Quỹ phát triển doanh nghiệp nhỏ và vừa thông qua hình thức cho vay gián tiếp hoặc tài trợ xây nhà xưởng, máy móc thì Quỹ sẽ sử dụng nguồn vốn nào để thực hiện và các thỏa thuận, nguyên tắc tài trợ cần tuân thủ những nội dung gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1057/2000]: Công ty đang tranh chấp với đối tác qua email về thỏa thuận trọng tài, nếu Hội đồng trọng tài quyết định thỏa thuận này vô hiệu thì công ty phải khiếu nại ra tòa thế nào và trong trường hợp không khiếu nại thì quy trình chuẩn bị phiên họp giải quyết tranh chấp sẽ được thực hiện ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1058/2000]: Công ty tôi định chạy chương trình khuyến mại tặng rượu mạnh cho khách hàng tại bệnh viện, đồng thời hiện đang thiếu quy chế dân chủ ở cơ sở và chưa thực hiện quan trắc môi trường lao động thì những rủi ro pháp lý và mức xử phạt tương ứng cho từng hành vi là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1059/2000]: Khi bị đối tác kiện ra trọng tài, nếu công ty muốn kiện ngược lại về vấn đề liên quan thì phải thực hiện quy trình nộp đơn kiện lại như thế nào và bản tự bảo vệ đi kèm cần đảm bảo những nội dung gì để vừa bảo vệ quyền lợi, vừa xác lập được thỏa thuận trọng tài nếu trước đó hai bên chưa ký văn bản chính thức?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1060/2000]: Trong trường hợp Chủ tịch Hội đồng thành viên đồng thời là người đại diện theo pháp luật duy nhất của công ty nhưng hiện đang bị tạm giam, công ty phải xử lý việc bầu người tạm thời điều hành Hội đồng thành viên và cử người đại diện theo pháp luật mới như thế nào, đồng thời điều kiện để cuộc họp bầu này diễn ra hợp lệ là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1061/2000]: Công ty có nhân viên làm việc không trọn thời gian vừa hết thời hạn tạm hoãn hợp đồng, nhưng trước đó công ty đã gửi thông báo đơn phương chấm dứt hợp đồng với người này thì giờ muốn hủy bỏ việc chấm dứt để nhận họ trở lại làm việc thì phải xử lý thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1062/2000]: Một nhân viên vừa chấm dứt hợp đồng lao động và muốn xin hỗ trợ học phí, tiền ăn để nâng cao kỹ năng nghề thì cần đáp ứng điều kiện gì về thời gian đóng bảo hiểm thất nghiệp, cách xác định thời gian đóng này và căn cứ nào để đối chiếu việc tham gia bảo hiểm?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1063/2000]: Công ty tôi đang có một nhãn hiệu đăng ký quốc tế qua hệ thống Madrid bị thông báo tạm thời từ chối tại Việt Nam, đồng thời muốn thay đổi địa chỉ chủ sở hữu và gia hạn hiệu lực cho một bằng độc quyền sáng chế hiện có thì mỗi việc phải xử lý như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1064/2000]: Công ty tôi đang hạch toán doanh thu từ tiền bán hàng và cung ứng dịch vụ, nhưng có một số khoản chi phí không có hóa đơn chứng từ và một số khoản tiền phạt vi phạm hành chính thì cách xác định thu nhập chịu thuế và phương pháp tính thuế thu nhập doanh nghiệp trong trường hợp này được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1065/2000]: Công ty tôi có đơn PCT vào giai đoạn quốc gia, nay muốn tách một phần giải pháp kỹ thuật sang đơn mới và gia hạn thời hạn nộp văn bản ủy quyền thì phải thực hiện như thế nào và thời điểm bắt đầu xử lý đơn PCT này được tính ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1066/2000]: Công ty tôi mới thành lập chưa đủ một năm, giờ muốn nộp hồ sơ xin hỗ trợ doanh nghiệp nhỏ và vừa thì phải xác định quy mô doanh nghiệp dựa trên căn cứ nào, quy trình kê khai ra sao và thứ tự ưu tiên được nhận hỗ trợ được tính như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1067/2000]: Công ty tôi đang hỗ trợ đối tác nước ngoài làm thủ tục hoàn thuế theo Hiệp định tránh đánh thuế hai lần và đồng thời làm hồ sơ hoàn thuế GTGT cho hàng xuất khẩu, vậy quy trình chuẩn bị hồ sơ cho hai trường hợp này khác nhau thế nào và cơ quan thuế sẽ ra quyết định hoàn thuế ra sao nếu công ty vẫn còn nợ thuế?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1068/2000]: Công ty tôi thuê lại lao động từ đối tác, vậy đối với nhóm nhân viên thuê lại này và những người làm việc không theo hợp đồng lao động tại xưởng, công ty cần phối hợp với bên cho thuê ra sao về an toàn vệ sinh lao động và phải thiết lập Hội đồng an toàn, vệ sinh lao động cơ sở với thành phần như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1069/2000]: Trong trường hợp đối tác làm mất tài sản thuê của công ty mà không thể thay thế hay sửa chữa, công ty nên chọn phương án hủy bỏ hợp đồng hay đơn phương chấm dứt thực hiện hợp đồng để đảm bảo quyền lợi về bồi thường và hoàn trả tài sản?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1070/2000]: Trong trường hợp công ty không đóng bảo hiểm tai nạn lao động, bệnh nghề nghiệp cho nhân viên, thì khi nhân viên này mắc bệnh thuộc danh mục của Bộ Y tế và suy giảm khả năng lao động từ 5% trở lên, công ty phải xử lý trách nhiệm chi trả và báo cáo thống kê như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1071/2000]: Công ty tôi là doanh nghiệp khởi nghiệp sáng tạo, vừa được một quỹ đầu tư cam kết rót vốn và đang có hợp đồng cung ứng cho một doanh nghiệp đầu chuỗi, vậy công ty cần đáp ứng phương thức lựa chọn nào để được hỗ trợ và sẽ được hỗ trợ những nội dung cụ thể nào về chi phí thuê mặt bằng cũng như tư vấn sở hữu trí tuệ?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1072/2000]: Để đảm bảo đúng quy định khi ghi sổ kế toán, công ty cần căn cứ vào loại chứng từ nào, nội dung sổ phải thể hiện những gì và hành vi tẩy xóa chứng từ này sẽ bị xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1073/2000]: Công ty muốn ký hợp đồng với một người đại diện theo pháp luật của cá nhân là người giám hộ do Tòa án chỉ định thì cần xác định những nội dung gì về phạm vi, thời hạn đại diện và trường hợp nào thì quyền đại diện này sẽ chấm dứt?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1074/2000]: Khi công ty quyết định giải thể, tôi cần thực hiện những công việc kế toán gì, đồng thời làm sao để đảm bảo hệ thống kiểm soát nội bộ vẫn vận hành an toàn tài sản và xử lý thế nào nếu có đoàn kiểm tra kế toán vào làm việc trong giai đoạn này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1075/2000]: Công ty tôi vừa bị thiệt hại nặng do thiên tai gây hư hỏng hàng hóa và nhà xưởng, nay muốn làm thủ tục giảm thuế tiêu thụ đặc biệt, miễn thuế sử dụng đất phi nông nghiệp và miễn lệ phí trước bạ cho tài sản được bồi thường tái định cư thì mỗi loại hồ sơ cần những giấy tờ gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1076/2000]: Khi thuê đơn vị vận chuyển giao hàng đến đối tác nhưng đến nơi không có người nhận, công ty cần xử lý việc gửi giữ tài sản này thế nào và trong trường hợp này bên vận chuyển cũng như công ty có những nghĩa vụ gì về chi phí và bảo đảm an toàn tài sản?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1077/2000]: Công ty cổ phần muốn thay đổi nội dung Điều lệ và bầu lại Hội đồng quản trị thì phải thực hiện quy trình triệu tập họp như thế nào, người triệu tập cần chuẩn bị những gì và hình thức thông qua nghị quyết cho hai nội dung này được quy định ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1078/2000]: Công ty muốn thuê một đơn vị quảng cáo để triển khai chương trình khuyến mại cho sản phẩm mới thì cần thực hiện hình thức hợp đồng thế nào và phải đảm bảo những nghĩa vụ gì trong quá trình vận hành?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1079/2000]: Công ty thuê đơn vị tổ chức trưng bày hàng hóa tại hội chợ nước ngoài thì cần thực hiện những nghĩa vụ gì, có quyền kiểm soát ra sao và lưu ý gì về việc bán hàng hóa thuộc diện phải có giấy phép tại đây?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1080/2000]: Công ty tôi muốn chuyển từ mô hình giao đại lý sang nhượng quyền thương mại để kiểm soát cách vận hành và nhãn hiệu, vậy công ty cần thực hiện thủ tục gì và quyền sở hữu hàng hóa lúc này thay đổi ra sao so với khi làm đại lý?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1081/2000]: Công ty muốn mở chi nhánh mới bằng cách dùng tài sản có đăng ký quyền sở hữu của thành viên để góp vốn thì cần chuẩn bị hồ sơ đăng ký hoạt động chi nhánh gồm những gì, thủ tục chuyển quyền sở hữu tài sản đó ra sao và ai là người ký biên bản giao nhận tài sản này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1082/2000]: Trong trường hợp công ty bị phát hiện vi phạm về thuế và hóa đơn thông qua một đoàn thanh tra, công ty cần thực hiện quyền giải trình như thế nào và ai là người có thẩm quyền ra quyết định xử phạt trong tình huống này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1083/2000]: Khi thành lập công ty, tôi cần quy định những nội dung gì về người đại diện theo pháp luật trong Điều lệ và mã số doanh nghiệp được cấp sau đó sẽ được sử dụng vào những mục đích cụ thể nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1084/2000]: Công ty tôi đáp ứng tiêu chí doanh nghiệp nhỏ và vừa thì được hưởng ưu đãi gì về đào tạo nguồn nhân lực và cơ quan nào có trách nhiệm ban hành, thực hiện các chính sách hỗ trợ này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1085/2000]: Công ty tôi đáp ứng tiêu chí doanh nghiệp nhỏ và vừa, hiện đang muốn áp dụng mức thuế suất thuế thu nhập doanh nghiệp thấp hơn thông thường và chế độ kế toán đơn giản cho đơn vị siêu nhỏ thì những hành vi nào của cơ quan hỗ trợ là bị nghiêm cấm trong quá trình thực hiện?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1086/2000]: Công ty muốn ký hợp đồng hợp tác với một đối tác để cùng khai thác mảnh đất, trong đó một bên đóng góp quyền sử dụng đất, một bên cung cấp dịch vụ vận hành và chia lợi nhuận thì nội dung hợp đồng cần đảm bảo những điều khoản chủ yếu nào và có lưu ý gì về mục đích sử dụng đất?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1087/2000]: Công ty tôi đã nộp phí và được cấp văn bằng bảo hộ nhãn hiệu, vậy tôi cần xác định những hành vi nào là đang sử dụng nhãn hiệu này và trong trường hợp nào tôi không có quyền ngăn cấm đối thủ cạnh tranh thực hiện các hành vi đó?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1088/2000]: Doanh nghiệp siêu nhỏ nộp thuế TNDN theo phương pháp tính trên thu nhập tính thuế thì phải thực hiện ghi sổ, áp dụng hệ thống tài khoản và danh mục sổ kế toán theo hướng dẫn nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1089/2000]: Công ty tôi đang nợ thuế kéo dài và bị cơ quan thuế ra quyết định thu tiền từ đối tác đang nợ công ty, vậy trong trường hợp này công ty có thể được xóa nợ thuế nếu bị thiệt hại do thiên tai không và rủi ro về việc bị công khai thông tin trên cổng thông tin điện tử của ngành thuế là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1090/2000]: Công ty tôi nộp đơn đăng ký chỉ dẫn địa lý nhưng bị thông báo dự định từ chối do thiếu bản mô tả tính chất đặc thù và không đáp ứng điều kiện bảo hộ, vậy quy trình xử lý của cơ quan quản lý và cách khắc phục để tránh bị từ chối cấp văn bằng bảo hộ là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1091/2000]: Công ty muốn chuyển giao dữ liệu khách hàng cho một đơn vị phân tích dữ liệu bên thứ ba để quảng cáo sản phẩm, đồng thời thuê một KOL cung cấp thông tin sản phẩm cho khách hàng thì phải thực hiện quy trình xin phép, quản lý dữ liệu và phối hợp trách nhiệm với các bên này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1092/2000]: Khi phát hiện đối tác nhập khẩu hàng hóa xâm phạm quyền tác giả về kho bãi, công ty cần cung cấp chứng cứ gì để yêu cầu cơ quan hải quan tạm dừng thủ tục và trong trường hợp nào hàng hóa đó sẽ bị buộc tiêu hủy?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1093/2000]: Công ty tôi muốn nhận nhượng quyền thương mại thì cần lập hợp đồng thế nào, có những nghĩa vụ cơ bản nào phải thực hiện và nếu xảy ra sự cố bất khả kháng dẫn đến vi phạm hợp đồng thì phải xử lý ra sao để được miễn trách nhiệm?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1094/2000]: Công ty muốn đăng ký bảo hộ đồng thời thiết kế bố trí mạch tích hợp, kiểu dáng công nghiệp cho sản phẩm và nhãn hiệu cho thương hiệu thì cần lưu ý điều kiện về khả năng phân biệt của nhãn hiệu là gì và nếu Cục Sở hữu trí tuệ nghi ngờ tính xác thực của thông tin trong đơn đăng ký thiết kế bố trí hoặc kiểu dáng công nghiệp thì công ty phải xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1095/2000]: Trong trường hợp công ty đang bị cưỡng chế thuế nhưng chủ doanh nghiệp muốn xuất cảnh định cư, đồng thời công ty đang làm thủ tục giải thể và xin gia hạn nộp thuế thì quy trình xử lý nghĩa vụ thuế và rủi ro đối với cá nhân chủ doanh nghiệp sẽ như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1096/2000]: Khi đối tác giao hàng kém chất lượng gây thiệt hại cho công ty, công ty có thể yêu cầu họ khắc phục hàng hóa, đòi tiền phạt vi phạm và yêu cầu bồi thường thiệt hại đồng thời không, và điều kiện để đòi bồi thường là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1097/2000]: Khi một doanh nghiệp nhỏ và vừa khởi nghiệp sáng tạo nhận đầu tư từ tổ chức tài chính nhà nước địa phương phối hợp với một quỹ đầu tư, thì quỹ này cần đáp ứng điều kiện gì để được lựa chọn cùng đầu tư và việc quản lý tài chính, chuyển vốn của nhà đầu tư nước ngoài trong mô hình này được thực hiện ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1098/2000]: Một nhân viên nữ làm việc theo hợp đồng lao động xác định thời hạn 2 năm tại công ty, sau khi hoàn tất thủ tục hưởng chế độ thai sản thì muốn nghỉ việc hẳn để hưởng lương hưu do bị suy giảm khả năng lao động, vậy trường hợp này cần đáp ứng điều kiện gì về đối tượng tham gia, hồ sơ thai sản và tiêu chuẩn hưởng lương hưu?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1099/2000]: Công ty đang tái cơ cấu tổ chức dẫn đến nhiều người mất việc, đối với những nhân viên đang tạm hoãn hợp đồng hoặc đang làm việc không trọn thời gian thì công ty phải xử lý việc nhận lại và cho thôi việc như thế nào để đúng luật?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1100/2000]: Công ty tôi vừa tham gia triển lãm thương mại với một số hàng hóa tạm nhập từ nước ngoài, đồng thời tại xưởng sản xuất đang thiếu báo cáo quan trắc môi trường lao động và chưa ban hành quy chế dân chủ ở cơ sở thì những rủi ro pháp lý và mức xử phạt tương ứng cho từng sai sót này là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1101/2000]: Công ty tôi đang đăng ký kiểu dáng công nghiệp cho sản phẩm mới, vậy cơ quan chức năng sẽ thẩm định điều kiện bảo hộ như thế nào, sau khi được cấp bằng thì thông tin nào sẽ được công bố công khai và tôi có thể tra cứu tình trạng pháp lý của văn bằng này ở đâu?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1102/2000]: Công ty tôi là TNHH hai thành viên trở lên, hiện đang làm thủ tục góp vốn bằng quyền sử dụng đất và muốn chỉ định một trong hai thành viên làm người đại diện theo pháp luật thì quy trình chuyển quyền sở hữu tài sản này phải thực hiện thế nào và ai là người ký biên bản giao nhận?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1103/2000]: Để xác định chính xác thời gian đóng bảo hiểm thất nghiệp cho nhân viên khi chấm dứt hợp đồng, công ty cần căn cứ vào hồ sơ nào và các khoản đóng này sẽ được hạch toán vào nguồn hình thành quỹ nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1104/2000]: Công ty muốn thay đổi người đại diện theo pháp luật để phù hợp với cơ cấu quản lý mới thì cần điều chỉnh nội dung nào trong Điều lệ và quy trình đăng ký thay đổi với cơ quan chức năng thực hiện ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1105/2000]: Khi phát hiện một đối thủ sao chép trái phép phần mềm của công ty để kinh doanh gây mất khách hàng, công ty cần xác định hành vi này là xâm phạm quyền tác giả theo tiêu chí nào và phải soạn đơn yêu cầu xử lý với những nội dung chính gì để yêu cầu bồi thường cả tổn thất về cơ hội kinh doanh?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1106/2000]: Công ty muốn thay đổi tên chủ sở hữu trên bằng độc quyền sáng chế, đồng thời thực hiện gia hạn hiệu lực văn bằng và thanh toán thù lao cho tác giả thì cần chuẩn bị hồ sơ gì và thời hạn thanh toán thù lao được tính như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1107/2000]: Công ty muốn giải quyết tranh chấp bằng trọng tài thông qua email thì hình thức này có hợp lệ không, và nếu Hội đồng trọng tài ra quyết định không chấp nhận thỏa thuận này thì công ty cần khiếu nại ra sao cũng như quy trình phiên họp giải quyết tranh chấp sau đó diễn ra thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1108/2000]: Công ty tôi nộp đơn La Hay qua cơ quan quản lý nhà nước về quyền sở hữu công nghiệp nhưng bị thông báo thiếu sót, nếu muốn gia hạn thời gian khắc phục hoặc yêu cầu tách đơn trước khi có quyết định từ chối thì phải thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1109/2000]: Để đăng ký nhận hỗ trợ từ nhà nước, công ty tôi cần xác định lĩnh vực hoạt động và kê khai quy mô doanh nghiệp như thế nào, và trong trường hợp đáp ứng nhiều mức hỗ trợ khác nhau thì sẽ được xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1110/2000]: Công ty tôi đang phát triển một ứng dụng di động mới và muốn tham gia vào chuỗi giá trị để cung ứng cho đối tác lớn, vậy công ty cần đáp ứng tiêu chí nào để được xác định là doanh nghiệp khởi nghiệp sáng tạo và được hưởng những hỗ trợ cụ thể nào về tư vấn sở hữu trí tuệ cũng như điều kiện để được lựa chọn hỗ trợ khi tham gia chuỗi giá trị?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1111/2000]: Khi công ty chuẩn bị sáp nhập và thực hiện kiểm kê tài sản, doanh nghiệp cần thiết lập hệ thống kiểm soát nội bộ ra sao để bảo đảm an toàn tài sản và phải phối hợp cung cấp tài liệu gì nếu có đoàn kiểm tra kế toán làm việc?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1112/2000]: Khi thiết lập hệ thống ghi chép tài chính, công ty cần đảm bảo sổ kế toán có những nội dung gì, căn cứ vào đâu để ghi sổ và việc tách riêng một số tài sản, nợ phải trả ra khỏi sổ này sẽ dẫn đến rủi ro pháp lý nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1113/2000]: Công ty tôi vừa bị hỏa hoạn gây thiệt hại nặng về hàng hóa và đất phi nông nghiệp, đồng thời có nhân viên bị tai nạn nghiêm trọng; để đề nghị giảm thuế thu nhập cá nhân, thuế tiêu thụ đặc biệt và thuế sử dụng đất phi nông nghiệp thì cần chuẩn bị những loại hồ sơ gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1114/2000]: Công ty tôi thuê lại một nhóm lao động từ đơn vị cung ứng để vận hành xưởng, vậy đối với nhóm này và nhân viên chính thức thì công ty phải xây dựng kế hoạch an toàn vệ sinh lao động hằng năm gồm những nội dung gì và cần phối hợp với bên cho thuê lao động ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1115/2000]: Hợp tác xã muốn ký hợp đồng dịch vụ để khai thác quyền sử dụng đất là tài sản chung của các thành viên thì cần tuân thủ điều kiện gì về nội dung hợp đồng và quy trình định đoạt tài sản này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1116/2000]: Trong trường hợp công ty không đóng bảo hiểm tai nạn lao động, bệnh nghề nghiệp cho nhân viên, nếu nhân viên này bị mắc bệnh nghề nghiệp và suy giảm khả năng lao động 10% thì công ty phải thực hiện báo cáo thống kê ra sao và cách tính khoản tiền tương ứng với chế độ trợ cấp một lần cho họ như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1117/2000]: Công ty mua một tài sản nhưng sau đó phát hiện người bán không có quyền bán tài sản này, vậy công ty nên đơn phương chấm dứt hay hủy bỏ hợp đồng và cách xử lý hoàn trả, bồi thường trong mỗi trường hợp khác nhau thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1118/2000]: Công ty tôi đang làm hồ sơ hoàn thuế GTGT cho dự án đầu tư và hỗ trợ đối tác nước ngoài hoàn thuế theo Hiệp định tránh đánh thuế hai lần, nếu sau này cơ quan thuế thanh tra phát hiện số thuế hoàn chưa đúng thì quy trình thu hồi và xử lý rủi ro pháp lý sẽ diễn ra như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1119/2000]: Doanh nghiệp siêu nhỏ khi thiết lập hệ thống ghi sổ kế toán và lập báo cáo tài chính thì phải quy định đơn vị tiền tệ như thế nào và cần sử dụng những mẫu sổ kế toán nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1120/2000]: Công ty muốn ủy quyền cho một đơn vị đại diện nộp đơn đăng ký chỉ dẫn địa lý cho sản phẩm đặc sản của mình thì giấy ủy quyền cần những nội dung gì, hồ sơ đơn đăng ký phải chuẩn bị những tài liệu nào và nếu đơn bị coi là không hợp lệ thì quy trình xử lý của cơ quan quản lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1121/2000]: Trong trường hợp Hệ thống thông tin quốc gia về đăng ký doanh nghiệp gặp sự cố kỹ thuật, công ty tôi muốn đăng ký tên mới thì quy trình cấp đăng ký sẽ thay đổi thế nào và việc kiểm tra tên trùng sẽ được thực hiện ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1122/2000]: Trong trường hợp hợp đồng lao động bị tuyên bố vô hiệu toàn bộ, công ty cần xử lý việc ký lại hợp đồng như thế nào, cách tính lương cho những ngày nghỉ lễ tết của nhân viên trong giai đoạn này ra sao và tiêu chuẩn thiết lập phòng vắt sữa mẹ tại nơi làm việc cho lao động nữ là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1123/2000]: Trong trường hợp công ty bị ấn định thuế do không xuất trình đủ hóa đơn chứng từ khi thanh tra, quy trình ban hành quyết định ấn định thuế diễn ra thế nào và nếu người đại diện pháp luật chưa nộp đủ số thuế này thì sẽ bị xử lý ra sao khi xuất cảnh?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1124/2000]: Công ty nộp đơn quốc tế để bảo hộ sở hữu công nghiệp thì quy trình xử lý đơn này ra sao, điều kiện để được cấp văn bằng bảo hộ là gì và sau khi có văn bằng, công ty có quyền ngăn cấm đối thủ sử dụng đối tượng đó trong những trường hợp nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1125/2000]: Công ty tôi đang là doanh nghiệp ưu tiên trong lĩnh vực hải quan nhưng vừa bị thiệt hại nặng do thiên tai, nếu công ty không thể nộp thuế đúng hạn và không cung cấp đủ số liệu đối chiếu cho cơ quan hải quan thì rủi ro về công khai thông tin và khả năng được xóa nợ thuế là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1126/2000]: Công ty thuê một KOL quảng bá sản phẩm và chia sẻ dữ liệu khách hàng cho bên vận chuyển, nhưng khi xảy ra tranh chấp về cách hiểu điều khoản trong hợp đồng mẫu và tính chính xác của thông tin quảng cáo thì việc giải quyết và phân định trách nhiệm giữa công ty, KOL và bên vận chuyển được thực hiện thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1127/2000]: Công ty phát hiện đối thủ sao chép trái phép phần mềm của mình để cho thuê thu lợi và làm mất khách hàng, vậy công ty cần xác định hành vi này xâm phạm quyền tác giả ở điểm nào, cách tính tổn thất về cơ hội kinh doanh ra sao và phải chuẩn bị những tài liệu, chứng cứ gì khi gửi đơn yêu cầu xử lý?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1128/2000]: Khi phát hiện đối thủ nhập khẩu hàng sao chép lậu tác phẩm của công ty, công ty cần cung cấp chứng cứ gì để chứng minh chủ thể quyền, gửi đơn đến cơ quan nào và hàng hóa vi phạm sẽ bị xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1129/2000]: Khi bên nhận quyền không thanh toán phí nhượng quyền và từ chối cho công ty kiểm tra định kỳ do gặp sự cố bất khả kháng, công ty cần xử lý quyền kiểm tra này thế nào và bên nhận quyền phải thực hiện nghĩa vụ thông báo ra sao để được miễn trách nhiệm?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1130/2000]: Công ty tôi đang nộp đơn đăng ký nhãn hiệu, kiểu dáng công nghiệp và thiết kế bố trí cho sản phẩm mới, vậy nếu Cục Sở hữu trí tuệ nghi ngờ tính xác thực thông tin trong đơn kiểu dáng hoặc thông báo đơn thiết kế bố trí có thiếu sót thì công ty phải xử lý thế nào để không bị từ chối cấp văn bằng, và nhãn hiệu cần đáp ứng điều kiện gì về khả năng phân biệt để được bảo hộ?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1131/2000]: Công ty tôi muốn đăng ký bảo hộ cho một mẫu mã sản phẩm mới, vậy quy trình thẩm định nội dung để đánh giá tính mới, tính sáng tạo được thực hiện ra sao, sau khi được cấp bằng thì những thông tin nào sẽ được công bố công khai và trong trường hợp nào văn bằng này có thể bị hủy bỏ hiệu lực?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1132/2000]: Khi đối tác giao hàng kém chất lượng, công ty muốn yêu cầu họ khắc phục, đòi tiền phạt vi phạm và bồi thường thiệt hại thì quy trình thực hiện ra sao và công ty cần làm gì để không bị giảm mức bồi thường?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1133/2000]: Trong trường hợp chủ hộ kinh doanh đột ngột mất tích và hộ kinh doanh này cũng đang làm thủ tục chấm dứt hoạt động nhưng vẫn còn nợ thuế, thì việc nộp thuế sẽ được xử lý thế nào và nếu muốn xin gia hạn nộp số thuế này thì hồ sơ được gửi qua những kênh nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1134/2000]: Khi một quỹ đầu tư khởi nghiệp sáng tạo bị giải thể do công ty quản lý quỹ phá sản, việc hạch toán tài chính phải tuân theo quy định nào và thứ tự ưu tiên thanh toán tài sản cho các bên liên quan được thực hiện ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1135/2000]: Công ty có một nhân viên làm việc theo hợp đồng 2 năm đang nghỉ thai sản thì đột ngột đủ tuổi nghỉ hưu, trường hợp này công ty cần xử lý hồ sơ thai sản như thế nào và thời điểm hưởng lương hưu của nhân viên này được xác định ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1136/2000]: Khi doanh nghiệp nhỏ và vừa không trả được nợ cho tổ chức cho vay, tổ chức này cần thực hiện những nghĩa vụ gì để yêu cầu Quỹ bảo lãnh tín dụng trả nợ thay và quy trình thẩm định hồ sơ này diễn ra như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1137/2000]: Công ty đang thực hiện sáp nhập và ảnh hưởng đến nhiều nhân sự, trong đó có một nhân viên đang tạm hoãn hợp đồng và một nhân viên làm việc không trọn thời gian, thì công ty phải xử lý phương án sử dụng lao động và quyền lợi cho hai nhóm này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1138/2000]: Công ty tôi hiện không tổ chức đối thoại định kỳ tại nơi làm việc, chưa tiến hành quan trắc môi trường lao động và đang nợ đóng bảo hiểm xã hội cho nhân viên thì sẽ đối mặt với những rủi ro pháp lý và hình thức xử lý nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1139/2000]: Công ty tôi và đối tác chỉ thỏa thuận giải quyết tranh chấp qua email, nay công ty khởi kiện ra trọng tài nhưng đến phiên họp lại vắng mặt không lý do, thì vụ việc sẽ được xử lý thế nào và nếu Hội đồng trọng tài cho rằng thỏa thuận qua email này vô hiệu thì công ty phải làm gì để khiếu nại?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1140/2000]: Công ty muốn thay đổi số lượng và phân chia quyền hạn của những người đại diện theo pháp luật thì phải thực hiện điều chỉnh trong văn bản nội bộ nào và thủ tục thông báo với cơ quan đăng ký kinh doanh ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1141/2000]: Công ty TNHH hai thành viên trở lên có thành viên góp vốn bằng quyền sử dụng đất thì quy trình chuyển quyền sở hữu tài sản này, thời hạn hoàn tất góp vốn và nội dung trên giấy chứng nhận phần vốn góp do người đại diện theo pháp luật ký phải thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1142/2000]: Trong trường hợp công ty bị kiện ra trọng tài nhưng không có văn bản thỏa thuận trước đó, công ty cần thể hiện sự đồng ý giải quyết tranh chấp này trong bản tự bảo vệ như thế nào và nếu phát hiện Trọng tài viên được chọn có lợi ích liên quan đến đối phương thì phải xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1143/2000]: Công ty tôi triển khai dự án đầu tư mới thuộc đối tượng được áp dụng thuế suất 10% trong 15 năm, vậy doanh thu để tính thuế được xác định như thế nào, phương pháp tính số thuế phải nộp ra sao và thời điểm bắt đầu tính thời gian hưởng thuế suất ưu đãi là khi nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1144/2000]: Công ty nộp đơn La Hay chỉ định Việt Nam nhưng bị thông báo từ chối do không đảm bảo tính thống nhất, vậy công ty cần xử lý thế nào để cứu các kiểu dáng công nghiệp này và nếu quá hạn 03 tháng do sự kiện bất khả kháng thì yêu cầu khôi phục thời hạn được thực hiện ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1145/2000]: Khi công ty muốn xây dựng lộ trình nâng cao tay nghề cho nhân viên dựa trên tiêu chuẩn kỹ năng nghề quốc gia, công ty cần căn cứ vào khung phân loại nào và những thông tin gì về chứng chỉ kỹ năng của người lao động cần được cập nhật vào cơ sở dữ liệu đăng ký lao động?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1146/2000]: Công ty tôi muốn tham gia chuỗi giá trị để được hỗ trợ kinh phí thuê mặt bằng tại cơ sở ươm tạo và tư vấn sở hữu trí tuệ thì cần đáp ứng tiêu chí lựa chọn nào và cơ quan nào có trách nhiệm hướng dẫn chi tiết các tiêu chí này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1147/2000]: Khi rà soát lại chứng từ chi tiền, công ty phát hiện một số phiếu chi bị tẩy xóa, thiếu chữ ký của kế toán trưởng và chưa được sắp xếp theo trình tự thời gian thì cách xử lý để đảm bảo đúng luật kế toán và những hành vi nào trong trường hợp này là bị nghiêm cấm?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1148/2000]: Công ty tôi vừa thực hiện dự án đầu tư sản xuất xăng sinh học và có phát sinh cả hàng hóa xuất khẩu, đồng thời đang làm thủ tục hoàn thuế cho đối tác nước ngoài theo Hiệp định tránh đánh thuế hai lần thì mỗi trường hợp này cần chuẩn bị những hồ sơ, giấy tờ gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1149/2000]: Doanh nghiệp tôi vừa gặp thiên tai gây thiệt hại nghiêm trọng đến tài nguyên đã kê khai, tài sản sản xuất và cả khu đất phi nông nghiệp đang sử dụng, vậy để được miễn giảm đồng thời thuế tài nguyên, thuế tiêu thụ đặc biệt và thuế sử dụng đất phi nông nghiệp thì hồ sơ cần chuẩn bị những gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1150/2000]: Khi đoàn kiểm tra kế toán yêu cầu cung cấp chứng từ nhưng công ty phát hiện tài liệu này đã bị mất, công ty cần thực hiện quy trình khắc phục thế nào và hệ thống kiểm soát nội bộ cần đảm bảo điều gì để tránh lặp lại rủi ro này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1151/2000]: Trong trường hợp nhân viên bị tai nạn khi đi công tác ngoài văn phòng và đồng thời mắc bệnh nghề nghiệp mà công ty chưa đóng bảo hiểm bắt buộc, công ty cần thực hiện báo cáo, bồi thường và cho nhân viên giám định mức suy giảm khả năng lao động như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1152/2000]: Hợp tác xã dự định ký hợp đồng hợp tác với một đối tác để cung cấp dịch vụ tư vấn trên một khu đất cụ thể, vậy hợp đồng này cần đảm bảo nội dung gì về quyền sử dụng đất và các thành viên hợp tác sẽ có quyền, nghĩa vụ gì trong quá trình thực hiện?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1153/2000]: Công ty nhập một lô hàng nhưng chất lượng không đạt tiêu chuẩn ngành và không đúng như thỏa thuận, vậy công ty có thể đơn phương chấm dứt hay hủy bỏ hợp đồng không và cách giải quyết hậu quả về tài sản, bồi thường trong mỗi trường hợp này khác nhau thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1154/2000]: Công ty tôi là đối tượng nộp thuế, hiện đang khiếu nại về một quyết định xử phạt vi phạm thủ tục thuế thì cơ quan quản lý thuế có quyền yêu cầu cung cấp hồ sơ gì, và nếu kết quả khiếu nại cho thấy công ty bị phạt sai thì ai là người có thẩm quyền ra quyết định xử phạt ban đầu cũng như xử lý hoàn trả tiền phạt cho công ty như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1155/2000]: Công ty tôi đang chuyển sang dùng hóa đơn điện tử và đồng thời thực hiện khấu trừ thuế TNCN cho nhân viên, vậy công ty cần xử lý các hóa đơn giấy cũ mua từ cơ quan thuế như thế nào và những loại chứng từ nào được dùng để quản lý thuế, phí, lệ phí?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1156/2000]: Công ty tôi thuê lại lao động từ một đơn vị cung ứng để vận hành xưởng cơ khí (ngành có nguy cơ cao về tai nạn), vậy việc đánh giá nguy cơ rủi ro về an toàn vệ sinh lao động cho nhóm này phải thực hiện như thế nào và trách nhiệm phối hợp giữa hai bên ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1157/2000]: Khi công ty nộp đơn đăng ký chỉ dẫn địa lý và đơn đăng ký sáng chế, nếu đơn không đáp ứng yêu cầu hình thức thì sẽ bị xử lý thế nào, và trong thời gian chờ công bố trên Công báo, thông tin trong đơn sáng chế được bảo vệ ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1158/2000]: Công ty muốn bảo hộ chỉ dẫn địa lý thông qua đề nghị quốc tế thì quy trình xử lý, điều kiện để được cấp văn bằng bảo hộ và quyền ngăn cấm đối thủ sử dụng chỉ dẫn này được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1159/2000]: Trong trường hợp công ty bị thiệt hại do dịch bệnh và đang làm thủ tục xóa nợ thuế, nếu công ty từ chối cung cấp thông tin theo yêu cầu của cơ quan thuế thì sẽ đối mặt với rủi ro bị công khai thông tin gì và trách nhiệm bồi thường ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1160/2000]: Trong trường hợp hợp đồng lao động bị tuyên bố vô hiệu toàn bộ, công ty cần xử lý việc ký lại hợp đồng như thế nào, cách tính lương cho những ngày nghỉ lễ tết trong thời gian chờ ký lại và các yêu cầu về buồng vệ sinh, buồng tắm tại nơi làm việc mà công ty bắt buộc phải đảm bảo là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1161/2000]: Doanh nghiệp siêu nhỏ nộp thuế TNDN theo phương pháp thu nhập tính thuế cần sử dụng những loại sổ kế toán nào và báo cáo tài chính lập ra sẽ cung cấp những thông tin gì cho chủ doanh nghiệp cũng như cơ quan Nhà nước?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1162/2000]: Nếu công ty bị cơ quan thuế ấn định thuế do không cung cấp đủ sổ sách kế toán và thông tin từ cơ quan đăng ký kinh doanh về việc thay đổi nội dung đăng ký doanh nghiệp, thì quy trình xử lý của cơ quan thuế sẽ diễn ra như thế nào và công ty phải đối mặt với những hậu quả pháp lý gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1163/2000]: Công ty tôi muốn mở rộng quy mô bằng cách đăng ký mới một doanh nghiệp con và một chi nhánh, vậy quy định về việc đặt tên để không bị trùng hoặc gây nhầm lẫn đối với hai đối tượng này khác nhau như thế nào và cơ quan nào sẽ quản lý việc đăng ký này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1164/2000]: Khi công ty phát hiện lô hàng nhập khẩu xâm phạm quyền tác giả, công ty cần cung cấp chứng cứ gì để yêu cầu cơ quan hải quan nào tạm dừng thủ tục và trong trường hợp nào thì lô hàng này có thể được buộc phân phối không nhằm mục đích thương mại?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1165/2000]: Công ty tôi đang khiếu nại về việc bị từ chối cấp Bằng độc quyền kiểu dáng công nghiệp do bị đánh giá là không có tính sáng tạo, vậy nếu giờ tôi muốn rút đơn khiếu nại thì thủ tục thực hiện ra sao và trường hợp nào cơ quan quản lý sẽ ra quyết định đình chỉ giải quyết khiếu nại này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1166/2000]: Công ty tôi là bên nhượng quyền, nếu không thể cung cấp tài liệu hướng dẫn và hỗ trợ kỹ thuật cho bên nhận quyền do sự kiện bất khả kháng, tôi cần xử lý thông báo thế nào và bên nhận quyền có nghĩa vụ gì trong việc phối hợp vận hành hệ thống lúc này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1167/2000]: Trong trường hợp công ty đang làm thủ tục giải thể nhưng trước đó có nộp hồ sơ gia hạn nộp thuế và hiện có số tiền thuế nộp thừa, thì việc xử lý nợ thuế còn lại và yêu cầu hoàn số tiền nộp thừa này được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1168/2000]: Công ty hợp danh là doanh nghiệp nhỏ và vừa khởi nghiệp sáng tạo muốn quyết định triển khai một dự án đầu tư mới để xin hỗ trợ giá thuê mặt bằng sản xuất thì cần tỷ lệ tán thành bao nhiêu từ Hội đồng thành viên và đối tượng nào sẽ được hưởng hỗ trợ này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1169/2000]: Công ty muốn thuê một bên thứ ba để quảng bá sản phẩm và thu thập dữ liệu khách hàng, vậy công ty cần quy định thế nào trong hợp đồng với khách hàng và hợp đồng với bên thứ ba để không vi phạm luật bảo vệ quyền lợi người tiêu dùng?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1170/2000]: Để được vay vốn gián tiếp từ Quỹ phát triển doanh nghiệp nhỏ và vừa, doanh nghiệp khởi nghiệp sáng tạo cần đáp ứng những điều kiện gì về vốn chủ sở hữu, phương án kinh doanh và các nguyên tắc chung về sử dụng vốn vay?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1171/2000]: Công ty tôi muốn đăng ký bảo hộ đồng thời nhãn hiệu cho logo, kiểu dáng công nghiệp cho sản phẩm và thiết kế bố trí cho chip điều khiển thì cần lưu ý điều kiện về đặc điểm tạo dáng, khả năng phân biệt của nhãn hiệu và quy định công bố thông tin đối với thiết kế bố trí như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1172/2000]: Đối tác giao hàng kém chất lượng và vi phạm cơ bản nghĩa vụ hợp đồng, công ty tôi có quyền tạm ngừng thực hiện hợp đồng không và ngoài ra có thể yêu cầu đối tác khắc phục hàng hóa cũng như trả tiền phạt như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1173/2000]: Công ty tôi tự ý cắt xén một video clip của nghệ sĩ và dùng bản nhạc nền trong đó để quảng cáo sản phẩm mà không xin phép, vậy hành vi này xâm phạm những quyền gì và công ty phải xác định tổn thất về cơ hội kinh doanh cho đối tác như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1174/2000]: Công ty đang cho một nhân viên làm việc không trọn thời gian tạm hoãn hợp đồng, nay hết thời hạn tạm hoãn nhưng công ty quyết định chấm dứt hợp đồng với nhân viên này thì phải xử lý việc nhận lại và thông báo chấm dứt như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1175/2000]: Công ty tôi muốn bổ sung thêm một người đại diện theo pháp luật để thuận tiện điều hành, vậy tôi cần quy định những nội dung gì trong Điều lệ và phải thực hiện công bố thông tin này như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1176/2000]: Công ty xây kho chứa chất độc hại gây ảnh hưởng đến nhà hàng xóm, đồng thời không thực hiện quan trắc môi trường lao động và không tổ chức đối thoại định kỳ thì phải xử lý bồi thường, khắc phục và chịu mức phạt hành chính như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1177/2000]: Công ty có một quản lý doanh nghiệp hưởng lương và một nhân viên nữ đang nghỉ thai sản; nếu nhân viên nữ này thôi việc trước khi sinh con thì ai là người nộp hồ sơ thai sản, và nếu vị quản lý trên đóng BHXH trên 35 năm thì khi nghỉ hưu sẽ được hưởng thêm khoản trợ cấp một lần như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1178/2000]: Công ty tôi đang giải quyết tranh chấp tại Trọng tài dựa trên thỏa thuận qua email, nhưng đối tác khiếu nại về thẩm quyền của Hội đồng trọng tài và người làm chứng quan trọng lại không đến phiên họp, vậy quy trình khiếu nại thẩm quyền ra Tòa án và cách xử lý để triệu tập người làm chứng này được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1179/2000]: Trong trường hợp công ty tôi xác định được toàn bộ tiền bán hàng và cung ứng dịch vụ nhưng không thể xác định được chi phí, thu nhập thì căn cứ tính thuế và phương pháp tính số thuế thu nhập doanh nghiệp phải nộp sẽ được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1180/2000]: Khi công ty lập biên bản giao nhận tài sản góp vốn để chuyển quyền sở hữu cho doanh nghiệp và đồng thời thiết lập bảng hiệu cho một địa điểm kinh doanh mới, thì chữ ký trên biên bản và cách đặt tên, hiển thị bảng hiệu này phải tuân thủ những quy định nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1181/2000]: Công ty muốn tách một phần danh mục hàng hóa từ đơn nhãn hiệu hiện tại sang đơn mới rồi nộp Đơn Madrid có nguồn gốc Việt Nam thì cần thực hiện thủ tục tách đơn thế nào, hồ sơ Đơn Madrid gồm những gì và nếu quá hạn nộp tài liệu bổ sung thì có thể gia hạn hoặc xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1182/2000]: Công ty tôi thuê lại lao động từ một đơn vị cung ứng, vậy đối với nhóm nhân sự thuê lại này và nhân viên chính thức, công ty cần xây dựng kế hoạch ứng cứu khẩn cấp gồm những nội dung chủ yếu nào và trách nhiệm phối hợp xử lý sự cố với bên cho thuê lao động ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1183/2000]: Công ty tôi đang sở hữu một bằng độc quyền sáng chế sắp hết hạn và một văn bằng bảo hộ chỉ dẫn địa lý cho đặc sản địa phương, vậy tôi cần làm thế nào để duy trì hiệu lực cho sáng chế và thực hiện sửa đổi bản mô tả tính chất đặc thù của sản phẩm mang chỉ dẫn địa lý này, đồng thời cơ quan nào sẽ chịu trách nhiệm xác định các đặc tính sản phẩm đó?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1184/2000]: Công ty tôi đang làm thủ tục giải thể và có số thuế GTGT đầu vào chưa khấu trừ hết, đồng thời có một khoản thuế nộp theo Hiệp định tránh đánh thuế hai lần cần hoàn thì quy trình lập hồ sơ cho hai trường hợp này khác nhau như thế nào và có điểm gì chung về mẫu đơn đề nghị?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1185/2000]: Để quản lý tài chính, công ty tôi muốn lập hai bộ sổ kế toán riêng biệt, dùng các hệ thống tài khoản khác nhau và lưu trữ chứng từ theo ý muốn thì cách làm này có đúng luật và rủi ro vi phạm là gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1186/2000]: Công ty tôi cùng đối tác ký hợp đồng hợp tác để khai thác một khu đất, trong đó một bên cung cấp dịch vụ quản lý vận hành để nhận phí, vậy khi hợp đồng này chấm dứt thì việc xử lý nợ và chia tài sản chung được thực hiện thế nào, và nội dung hợp đồng về quyền sử dụng đất cần tuân thủ những điều kiện gì?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1187/2000]: Khi công ty thực hiện sáp nhập một đơn vị kế toán khác, công ty cần triển khai các bước bàn giao kế toán nào, đồng thời phải thiết lập hệ thống kiểm soát nội bộ và phối hợp với đoàn kiểm tra kế toán ra sao để đảm bảo tính pháp lý?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1188/2000]: Khi công ty đơn phương chấm dứt hoặc hủy bỏ hợp đồng với đối tác, việc thanh toán cho phần nghĩa vụ đã thực hiện sẽ được xử lý thế nào nếu trước đó hai bên không thỏa thuận rõ ràng về giá và phương thức thanh toán?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1189/2000]: Khi nhân viên bị bệnh nghề nghiệp hoặc tai nạn lúc đi làm, công ty cần thực hiện báo cáo thống kê gì và trong trường hợp không đóng bảo hiểm bắt buộc thì phải chi trả những khoản tương ứng với chế độ từ Quỹ bảo hiểm tai nạn lao động, bệnh nghề nghiệp nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1190/2000]: Công ty tôi đang vận hành dự án nhà ở xã hội cho người lao động, đồng thời có một số cơ sở sản xuất bị thiệt hại nặng do thiên tai và có đất phi nông nghiệp, vậy tôi cần chuẩn bị những bộ hồ sơ gì để đề nghị miễn tiền sử dụng đất cho dự án, giảm thuế tiêu thụ đặc biệt do thiên tai và miễn giảm thuế sử dụng đất phi nông nghiệp?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1191/2000]: Công ty tôi đã nộp phí và được cấp văn bằng bảo hộ cho một kiểu dáng công nghiệp, vậy công ty có những quyền tài sản nào và trong trường hợp nào công ty không được quyền ngăn cấm đối thủ cạnh tranh sử dụng kiểu dáng này?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1192/2000]: Công ty tôi vừa bị phát hiện cho đối tác mượn hóa đơn đặt in chưa phát hành, đồng thời chậm nộp hồ sơ khai thuế hơn 100 ngày có phát sinh thuế và cung cấp thông tin tài khoản khách hàng cho cơ quan thuế chậm 10 ngày thì sẽ đối mặt với những mức phạt và biện pháp khắc phục hậu quả nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1193/2000]: Công ty tôi muốn đăng ký bảo hộ chỉ dẫn địa lý cho sản phẩm đặc sản vùng miền thì cần chuẩn bị những tài liệu gì trong đơn, điều kiện nào để đơn được coi là hợp lệ và sau đó đơn sẽ được xử lý thẩm định nội dung như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1194/2000]: Khi công ty thực hiện khấu trừ thuế TNCN cho nhân viên nhưng đồng thời đang làm thủ tục chuyển sang sử dụng hóa đơn điện tử và ngưng sử dụng mã số thuế, công ty cần xử lý các hóa đơn cũ và lập chứng từ khấu trừ thuế vào thời điểm nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1195/2000]: Khi thành lập doanh nghiệp trong khu công nghệ cao, tôi cần nộp hồ sơ đăng ký tên tại cơ quan nào và nếu cơ quan này từ chối tên dự kiến vì lý do trùng lặp thì tôi có quyền xử lý ra sao?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1196/2000]: Công ty vận hành hệ thống đường ống phân phối khí ký hợp đồng lao động sai thẩm quyền dẫn đến bị tuyên bố vô hiệu toàn bộ, vậy việc xử lý hợp đồng này, cách tính lương cho những ngày nghỉ lễ tết và quyền lợi về thời giờ làm việc đặc thù của nhân viên sẽ được thực hiện như thế nào?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1197/2000]: Công ty tôi vừa phát hiện bị mất một số hóa đơn đã mua của cơ quan thuế nhưng chưa lập và đồng thời phát hiện phần mềm hóa đơn điện tử đang dùng không đảm bảo nguyên tắc pháp luật, vậy trường hợp này công ty sẽ bị xử lý như thế nào và ai là đối tượng chịu phạt?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1198/2000]: Khi công ty dùng một bất động sản đầu tư để góp vốn vào công ty liên kết, kế toán cần xử lý giá trị tài sản này như thế nào và có được hạch toán chi phí giao dịch liên quan vào tài khoản chi phí sản xuất kinh doanh dở dang không, đồng thời lưu ý gì về việc xác định nghĩa vụ thuế?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!
Start [1199/2000]: Khi phát hiện đối tác nhập khẩu hàng hóa xâm phạm quyền tác giả của công ty, để đề nghị cơ quan hải quan tạm dừng làm thủ tục hải quan thì công ty cần cung cấp những loại chứng cứ nào để chứng minh tư cách chủ thể quyền và chứng minh hành vi xâm phạm?

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Đã hoàn tất quá trình cập nhật và lưu file!