# 0. Setup

In [ ]:
import os

os.environ["HF_TOKEN"] = "SECRET_KEY"

# 1. Load Dataset

In [2]:
from src.preprocess_parquet import load
import pandas as pd


df = load('data/processed/phapdien_processed.parquet')
# df = df.drop(columns=['docs_vbpl_id', 'docs_title', 'status', 'agency_name', 'topic_title', 'source_links'])
df

,legal_type,docs_code,docs_title,article_index,article_title,source_note_text,source_links,topic_title,subject_title,content_text,content_word_count,content_clause_count
40313,Thông tư,18/2023/TT-BTC,Thông tư số 18/2023/TT-BTC,Điều 6,Điều 39.13.TT.70.6. Cách tính và thực hiện bù ...,"(Điều 6 Thông tư số 18/2023/TT-BTC, có hiệu lự...","[{'text': '(Điều 6 Thông tư số 18/2023/TT-BTC,...","Trật tự, an toàn xã hội",Xử lý vi phạm hành chính,"{'title': '', 'content': [{'text': '1. Cách tí...",1735769,63
27764,Nghị định,38/2016/NĐ-CP,Nghị định số 38/2016/NĐ-CP,Điều 8,Điều 27.2.NĐ.1.8. Bảo vệ hành lang kỹ thuật cô...,"(Điều 8 Nghị định số 38/2016/NĐ-CP, có hiệu lự...","[{'text': '(Điều 8 Nghị định số 38/2016/NĐ-CP,...",Tài nguyên,Khí tượng thủy văn,"{'title': '', 'content': [{'title': '1. Bảo vệ...",116725,22
22725,Thông tư,36/2014/TT-BNNPTNT,Thông tư số 36/2014/TT-BNNPTNT,Điều 2,Điều 24.1.TT.12.2. Giải thích từ ngữ,"(Điều 2 Thông tư số 36/2014/TT-BNNPTNT, có hiệ...",[{'text': '(Điều 2 Thông tư số 36/2014/TT-BNNP...,"Nông nghiệp, nông thôn",Bảo vệ và kiểm dịch thực vật,"{'title': 'Trong Thông tư này, các từ ngữ dưới...",95736,30
18195,Nghị định,145/2020/NĐ-CP,Nghị định số 145/2020/NĐ-CP,Điều 57,Điều 20.2.NĐ.3.57. Tiền lương làm thêm giờ vào...,"(Điều 57 Nghị định số 145/2020/NĐ-CP, có hiệu ...",[{'text': '(Điều 57 Nghị định số 145/2020/NĐ-C...,Lao động,Lao động,{'title': 'Người lao động làm thêm giờ vào ban...,89094,14
2096,Thông tư,20/2017/TT-BTTTT,Thông tư số 20/2017/TT-BTTTT,Điều 3,Điều 3.1.TT.3.3. Phân cấp tổ chức thực hiện ứn...,"(Điều 3 Thông tư số 20/2017/TT-BTTTT, có hiệu ...",[{'text': '(Điều 3 Thông tư số 20/2017/TT-BTTT...,"Bưu chính, viễn thông",An toàn thông tin mạng,{'title': 'Phân cấp tổ chức thực hiện ứng cứu ...,64554,14
...,...,...,...,...,...,...,...,...,...,...,...,...
27708,Thông tư,21/2016/TT-BTNMT,Thông tư số 21/2016/TT-BTNMT,Điều 1,Điều 27.1.TT.53.1. Ban hành kèm theo Thông tư ...,(Điều 1 Thông tư số 21/2016/TT-BTNMT Ban hành ...,[{'text': '(Điều 1 Thông tư số 21/2016/TT-BTNM...,Tài nguyên,Đo đạc và bản đồ,{'text': 'Danh muc_21_2016_TT-BTNMT.doc'},2,0
27716,Thông tư,19/2017/TT-BTNMT,Thông tư số 19/2017/TT-BTNMT,Điều 1,Điều 27.1.TT.62.1. Ban hành kèm theo Thông tư ...,(Điều 1 Thông tư số 19/2017/TT-BTNMT Ban hành ...,[{'text': '(Điều 1 Thông tư số 19/2017/TT-BTNM...,Tài nguyên,Đo đạc và bản đồ,{'text': 'Danh muc_19_2017_TT-BTNMT.doc'},2,0
27718,Thông tư,48/2013/TT-BTNMT,Thông tư số 48/2013/TT-BTNMT,Điều 1,Điều 27.1.TT.26.1. Ban hành kèm theo Thông tư ...,(Điều 1 Thông tư số 48/2013/TT-BTNMT Ban hành ...,[{'text': '(Điều 1 Thông tư số 48/2013/TT-BTNM...,Tài nguyên,Đo đạc và bản đồ,{'text': 'Danh muc_48_2013_TT-BTNMT.doc'},2,0
27691,Thông tư,38/2013/TT-BTNMT,Thông tư số 38/2013/TT-BTNMT,Điều 1,Điều 27.1.TT.21.1. Ban hành kèm theo Thông tư ...,(Điều 1 Thông tư số 38/2013/TT-BTNMT Ban hành ...,[{'text': '(Điều 1 Thông tư số 38/2013/TT-BTNM...,Tài nguyên,Đo đạc và bản đồ,{'text': 'Danh muc_38_2013_TT-BTNMT.doc'},2,0
44248,Thông tư,04/2018/TT-BXD,Thông tư số 04/2018/TT-BXD,Điều 1,Điều 41.9.TT.4.1. Ban hành kèm theo Thông tư n...,(Điều 1 Thông tư số 04/2018/TT-BXD Ban hành Qu...,[{'text': '(Điều 1 Thông tư số 04/2018/TT-BXD ...,"Văn hóa, thể thao, du lịch",Quảng cáo,{'text': 'QuychuankemThongtu04-2018-BXD.doc'},1,0

# 2. HyDE setup

In [ ]:
!pip install llama-cpp-python \
    --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121 -q



!mkdir -p /kaggle/working/models

!wget -q --show-progress \
    "https://huggingface.co/bartowski/Qwen2.5.1-Coder-7B-Instruct-GGUF/resolve/main/Qwen2.5.1-Coder-7B-Instruct-Q4_K_M.gguf" \
    -O /saved_model/Qwen2.5.1-Coder-7B-Instruct-Q4_K_M.gguf

MODEL_PATH = "/saved_model//Qwen2.5.1-Coder-7B-Instruct-Q4_K_M.gguf"

In [ ]:
from src.precision_retriever import LlamaHyDEProcessor

print("[INFO] Đang nạp Local LLM (4-bit) cho HyDE...")


# Khởi tạo HyDE
hyde_processor = LlamaHyDEProcessor(
    model_path = MODEL_PATH,
    main_gpu=0,
    n_ctx = 4096,
    max_new_tokens = 256,
    system_prompt = """
    Bạn là một chuyên gia phân tích pháp lý, chịu trách nhiệm Phân rã truy vấn (Query Decomposition) và Xây dựng văn bản quy phạm giả định (Hypothetical Document) nhằm tối ưu hóa việc truy hồi tài liệu pháp luật Việt Nam. 

    Nhiệm vụ của bạn là chuyển đổi câu hỏi mang tính chất thắc mắc của người dùng thành một đoạn văn bản mô tả giả định có văn phong, cấu trúc tương đương với các nghị định, thông tư hoặc điều luật.
    
    
    Đoạn văn bản giả định bắt buộc phải trích xuất và thể hiện được các yếu tố sau:
    1. Đối tượng (Chủ thể): Xác định rõ các cá nhân, cơ quan, tổ chức hoặc thực thể có liên quan trực tiếp đến tình huống.
    2. Ý định: Thể hiện rõ mục đích, nguyện vọng, hoặc nhu cầu cốt lõi của đối tượng.
    3. Hành vi/Nghĩa vụ: Mô tả cụ thể các hành động, trách nhiệm, quy trình hoặc quyền lợi mà đối tượng phải thực hiện, được phép thực hiện, hoặc bị nghiêm cấm.
    
    Yêu cầu nghiêm ngặt về mặt thể hiện:
    - Văn phong pháp lý: Sử dụng hoàn toàn câu tường thuật, câu khẳng định hoặc câu điều kiện hành chính (Ví dụ sử dụng các cấu trúc: "Trường hợp cá nhân có nguyện vọng...", "Chủ thể có nghĩa vụ...", "Cơ quan có thẩm quyền thực hiện..."). 
    - Không đặt câu hỏi: Tuyệt đối không dùng câu nghi vấn, không đặt câu hỏi ngược lại, không có dấu chấm hỏi.
    - Kiểm soát thông tin (Chống nhiễu truy hồi): Chỉ sử dụng các thuật ngữ có sẵn trong câu hỏi gốc. Tuyệt đối KHÔNG tự ý đưa vào tên các bộ luật cụ thể (như Luật Dân sự, Luật Đất đai...), không tự bịa số hiệu điều/khoản, và không tự thêm các số liệu, thời gian, thời hạn cụ thể nằm ngoài câu hỏi. Thay vào đó, hãy dùng từ ngữ tổng quát như "theo quy định của pháp luật", "trong thời hạn quy định", "tại cơ quan có thẩm quyền".
    - Trình bày mỗi nhóm quan hệ Chủ thể - Ý định - Hành vi thành một câu đơn độc lập.
    - Ngôn ngữ: Chỉ sử dụng Tiếng Việt.
    - Định dạng đầu ra: Chỉ trả về duy nhất một đoạn văn bản giả định (khoảng 50 - 100 từ). Tuyệt đối không chào hỏi, không giải thích lý do, không thêm nhận xét hay bất kỳ ký tự dẫn chuyện nào khác.    
    """
)

print("[SUCCESS] Local HyDE đã sẵn sàng.")

In [ ]:
print(hyde_processor.enhance(
    "Các cơ sở ươm tạo và khu làm việc chung được hưởng những chính sách hỗ trợ nào về thuế và đất đai"
))

# 3. Recall Retriever setup

## 3.1. Data representation & BM25

In [3]:
from src.recall_retriever import BM25
from src.data_presentation import Corpus, HierarchicalCorpus

corpus_simple = Corpus()
corpus_hier = HierarchicalCorpus(
    alpha = 0.5,
    title_blending = True
)

bm25_raw = BM25(
    name="BM25_ra",
    corpus= corpus_simple,
    top_k=100,
    norm=0.75,
    use_segmentation=True
)
bm25_hier = BM25(
    name="BM25_hi",
    corpus= corpus_hier,
    top_k=5000,     # vì top-K này dựa trên bản Articles bị chunk (mảnh) rồi. Nên để top_k lớn hơn ít nhất 6-10 lần số lượng cần lấy, để đảm bảo đúng ranking.
    norm=0.25,
    use_segmentation=True
)

## 3.2 Bi-Encoder

In [4]:
from sentence_transformers import SentenceTransformer
from src.recall_retriever import Dense
import torch

dense_model = SentenceTransformer(
    "keepitreal/vietnamese-sbert",
    token=os.environ.get("HF_TOKEN"),
    model_kwargs={"torch_dtype": torch.float16},
    device="cuda" 
)
print(f"[SUCCESS] Dense Model sẵn sàng trên: {dense_model.device}")


dense_raw = Dense(
    corpus_simple, dense_model,
    batch_size=8,
    top_k = 200, 
    M=32, ef_construction=512, ef_search=256,
    index_type='Flat', name='DENSE_ra' 
)


dense_hier = Dense(
    corpus_hier, dense_model,
    batch_size=2,
    top_k = 5000, 
    M=256, ef_construction=4096, ef_search=2048,
    index_type='HNSW', name='DENSE_hi' 
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[SUCCESS] Dense Model sẵn sàng trên: cuda:0

# 4. Precision Retriever setup

In [5]:
from sentence_transformers import CrossEncoder
from src.precision_retriever import CrossEncoderReranker

reranker_model = CrossEncoder(
    "BAAI/bge-reranker-v2-m3", 
    model_kwargs={"torch_dtype": torch.float16},
    device="cuda" 
)
print(f"[SUCCESS] Cross-Encoder sẵn sàng trên: {reranker_model.model.device}")

# Khởi tạo class
crossEncoder = CrossEncoderReranker(
    model=reranker_model,
    name="CE",
    batch_size=8
)

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

[SUCCESS] Cross-Encoder sẵn sàng trên: cuda:0

# 5. Pipeline construct & Initial fitting

In [6]:
from src.retrieval_pipeline import RetrievalPipeline


retriever = RetrievalPipeline(
    data = df['content_text'],
    recallLayers=[dense_hier, bm25_hier],
    precisionLayers=[crossEncoder],
    save_folder="saved_model/phapdien"
)

[INFO] Đang build Corpuses
[INFO] [1/1] Đang build <class 'src.data_presentation.HierarchicalCorpus'>
[INFO] Đang load saved models cho lớp Recall Retrievers
[INFO] [1/2] Đang load <class 'src.recall_retriever.Dense'>
[INFO] [1/2] Đang load <class 'src.recall_retriever.BM25'>

# 6. Manual Evaluation

In [7]:
score = retriever.retrieve("Công ty sản xuất nhỏ và vừa tham gia chuỗi giá trị sẽ được hỗ trợ những nội dung gì?")

score_board = pd.concat([df[['docs_code', 'article_index']], score], axis=1)

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
score_board.sort_values(by="BM25_hi_score", ascending=False).head(16)

,docs_code,article_index,DENSE_hi_score,DENSE_hi_comment,BM25_hi_score,BM25_hi_comment,RRF_score,CE_score
8992,80/2021/NĐ-CP,Điều 26,0.599985,[3],17.234537,[1],0.028739,0.984863
8671,80/2021/NĐ-CP,Điều 1,0.694603,[],16.996542,[],0.032522,0.905762
8985,04/2017/QH14,Điều 19,0.670655,"[1, 1]",15.848157,"[2, 4]",0.031746,0.998047
23405,58/2024/NĐ-CP,Điều 24,0.684530,[],15.831905,[],0.031754,0.966797
9008,39/2019/NĐ-CP,Điều 16,0.618677,"[1, 1]",14.179266,"[3, 2]",0.029083,0.941895
8736,80/2021/NĐ-CP,Điều 32,0.602238,"[3, 4]",14.106615,"[3, 1]",0.027652,0.874512
8718,80/2021/NĐ-CP,Điều 4,0.654377,[4],13.835903,[4],0.030550,0.983398
9086,80/2021/NĐ-CP,Điều 28,0.551922,"[1, 5]",13.229777,"[1, 5]",0.022282,0.779785
8988,80/2021/NĐ-CP,Điều 24,0.620056,"[2, 1]",12.785608,"[2, 3]",0.028577,0.985352
8993,80/2021/NĐ-CP,Điều 27,0.547331,[2],12.717123,[2],0.021480,0.913574
8915,55/2019/NĐ-CP,Điều 9,0.469584,"[3, 4]",11.772307,"[3, 4]",0.016460,0.422607
8929,80/2021/NĐ-CP,Điều 13,0.540831,"[2, 1]",11.513651,"[2, 3]",0.020341,0.177246
8918,55/2019/NĐ-CP,Điều 12,0.587692,"[3, 3]",11.243547,[4],0.024568,0.029877
8919,55/2019/NĐ-CP,Điều 13,0.569139,"[3, 2]",11.194885,"[3, 1]",0.022523,0.093689
8934,80/2021/NĐ-CP,Điều 14,0.465289,"[3, 1]",10.920711,[4],0.015503,0.108215
8696,52/2023/TT-BTC,Điều 1,0.551709,[1],10.836029,[1],0.020677,0.932617

In [9]:
score_board.sort_values(by="DENSE_hi_score", ascending=False).head(16)

,docs_code,article_index,DENSE_hi_score,DENSE_hi_comment,BM25_hi_score,BM25_hi_comment,RRF_score,CE_score
8671,80/2021/NĐ-CP,Điều 1,0.694603,[],16.996542,[],0.032522,0.905762
23405,58/2024/NĐ-CP,Điều 24,0.684530,[],15.831905,[],0.031754,0.966797
8985,04/2017/QH14,Điều 19,0.670655,"[1, 1]",15.848157,"[2, 4]",0.031746,0.998047
8718,80/2021/NĐ-CP,Điều 4,0.654377,[4],13.835903,[4],0.030550,0.983398
8989,06/2022/TT-BKHĐT,Điều 17,0.636427,"[1, 3]",7.429907,"[1, 3]",0.022007,0.198730
9095,04/2017/QH14,Điều 27,0.635998,[1],9.295351,[1],0.025253,0.068909
8908,04/2017/QH14,Điều 13,0.635604,"[2, 1]",10.116553,"[2, 2]",0.026161,0.773926
9093,80/2021/NĐ-CP,Điều 30,0.630088,[4],10.549658,[3],0.027206,0.110657
8690,07/2020/TT-BKHCN,Điều 1,0.629403,[],10.654466,[],0.027480,0.015076
9097,04/2017/QH14,Điều 29,0.623783,[1],9.927971,"[2, 2]",0.025397,0.231323
8988,80/2021/NĐ-CP,Điều 24,0.620056,"[2, 1]",12.785608,"[2, 3]",0.028577,0.985352
8949,80/2021/NĐ-CP,Điều 20,0.619008,[3],9.797529,[2],0.024878,0.030853
9008,39/2019/NĐ-CP,Điều 16,0.618677,"[1, 1]",14.179266,"[3, 2]",0.029083,0.941895
8987,06/2022/TT-BKHĐT,Điều 16,0.613262,"[2, 3]",NaN,[],0.013514,0.001028
8920,55/2019/NĐ-CP,Điều 14,0.611357,"[7, 1]",9.081165,"[3, 2]",0.022767,0.022766
8910,55/2019/NĐ-CP,Điều 4,0.610979,"[4, 2]",9.712259,[5],0.023575,0.115173

In [10]:
score_board.sort_values(by="RRF_score", ascending=False).head(16)

,docs_code,article_index,DENSE_hi_score,DENSE_hi_comment,BM25_hi_score,BM25_hi_comment,RRF_score,CE_score
8671,80/2021/NĐ-CP,Điều 1,0.694603,[],16.996542,[],0.032522,0.905762
23405,58/2024/NĐ-CP,Điều 24,0.684530,[],15.831905,[],0.031754,0.966797
8985,04/2017/QH14,Điều 19,0.670655,"[1, 1]",15.848157,"[2, 4]",0.031746,0.998047
8718,80/2021/NĐ-CP,Điều 4,0.654377,[4],13.835903,[4],0.030550,0.983398
9008,39/2019/NĐ-CP,Điều 16,0.618677,"[1, 1]",14.179266,"[3, 2]",0.029083,0.941895
8992,80/2021/NĐ-CP,Điều 26,0.599985,[3],17.234537,[1],0.028739,0.984863
8988,80/2021/NĐ-CP,Điều 24,0.620056,"[2, 1]",12.785608,"[2, 3]",0.028577,0.985352
8736,80/2021/NĐ-CP,Điều 32,0.602238,"[3, 4]",14.106615,"[3, 1]",0.027652,0.874512
8690,07/2020/TT-BKHCN,Điều 1,0.629403,[],10.654466,[],0.027480,0.015076
9093,80/2021/NĐ-CP,Điều 30,0.630088,[4],10.549658,[3],0.027206,0.110657
8908,04/2017/QH14,Điều 13,0.635604,"[2, 1]",10.116553,"[2, 2]",0.026161,0.773926
9097,04/2017/QH14,Điều 29,0.623783,[1],9.927971,"[2, 2]",0.025397,0.231323
9095,04/2017/QH14,Điều 27,0.635998,[1],9.295351,[1],0.025253,0.068909
8949,80/2021/NĐ-CP,Điều 20,0.619008,[3],9.797529,[2],0.024878,0.030853
8950,80/2021/NĐ-CP,Điều 21,0.596114,"[3, 2]",10.613852,"[3, 3]",0.024869,0.038452
8918,55/2019/NĐ-CP,Điều 12,0.587692,"[3, 3]",11.243547,[4],0.024568,0.029877

In [11]:
final = score_board.sort_values(by="CE_score", ascending=False).head(100)
final.to_csv("trash/results_good/bge_results.csv")
final.head(10)

,docs_code,article_index,DENSE_hi_score,DENSE_hi_comment,BM25_hi_score,BM25_hi_comment,RRF_score,CE_score
8985,04/2017/QH14,Điều 19,0.670655,"[1, 1]",15.848157,"[2, 4]",0.031746,0.998047
8988,80/2021/NĐ-CP,Điều 24,0.620056,"[2, 1]",12.785608,"[2, 3]",0.028577,0.985352
8992,80/2021/NĐ-CP,Điều 26,0.599985,[3],17.234537,[1],0.028739,0.984863
8718,80/2021/NĐ-CP,Điều 4,0.654377,[4],13.835903,[4],0.030550,0.983398
23405,58/2024/NĐ-CP,Điều 24,0.684530,[],15.831905,[],0.031754,0.966797
9008,39/2019/NĐ-CP,Điều 16,0.618677,"[1, 1]",14.179266,"[3, 2]",0.029083,0.941895
8696,52/2023/TT-BTC,Điều 1,0.551709,[1],10.836029,[1],0.020677,0.932617
8993,80/2021/NĐ-CP,Điều 27,0.547331,[2],12.717123,[2],0.021480,0.913574
8671,80/2021/NĐ-CP,Điều 1,0.694603,[],16.996542,[],0.032522,0.905762
8991,06/2022/TT-BKHĐT,Điều 18,0.578756,[1],9.763990,[2],0.020753,0.895508